package org.apache.jsp.baf.jsp.uimain.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.regaltec.baf.org.user.common.valueobj.UserVO;
import com.regaltec.baf.org.user.ui.control.UserLoginBean;

public final class more_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/baf/jsp/ui/js/config.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String locale = request.getLocale().toString();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html> \r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");

   String getPath = request.getContextPath();
   String getLocal = request.getLocale().toString();

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">  \r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/language/zh_CN.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery-1.7.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery.json-2.4.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/in-min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/css/bootstrap-responsive.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/css/ccssoft_extend.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 6]>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/css/bootstrap-ie6.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/css/ie.css\">\r\n");
      out.write("  <script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/js/bootstrap-ie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script>\r\n");
      out.write("console = window.console || {log:function(){}};\r\n");
      out.write("In.add('mainCSS',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/css/main.css',type:'css',charset:'utf-8'});\r\n");
      out.write("\r\n");
      out.write("In.add('ccssoft',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/ccssoft.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('underscore',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/underscore-min.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('backbone',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/backbone-min.js',type:'js',charset:'utf-8',rely:['underscore']});\r\n");
      out.write("\r\n");
      out.write("In.add('json',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/json2.js',type:'js',charset:'utf-8'});\r\n");
      out.write("//dragable\r\n");
      out.write("In.add('dragable',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery.dragable.js',type:'js',charset:'utf-8',rely:['ccssoft']});\r\n");
      out.write("\r\n");
      out.write("In.add('extJson',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/ext.json.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('main',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/main.js',type:'js',charset:'utf-8'});\r\n");
      out.write("\r\n");
      out.write("In.add('all',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/ccssoftUI/ccssoft.all.js',type:'js',charset:'utf-8',rely:['main']});\r\n");
      out.write("\r\n");
      out.write("//åé¡µæ§ä»¶\r\n");
      out.write("In.add('pageSize',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery.boot_pageSize.js',type:'js',charset:'utf-8'});\r\n");
      out.write("\r\n");
      out.write("//artTemplate\r\n");
      out.write("In.add('template',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/template.min.js',type:'js',charset:'utf-8'});\r\n");
      out.write("//dhtmlxtree \r\n");
      out.write("In.add('dhtmlxtreeCSS',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/dhtmlxtree/dhtmlxtree.css',type:'css',charset:'utf-8'});\r\n");
      out.write("In.add('dhtmlxcommon',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/dhtmlxtree/dhtmlxcommon.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('dhtmlxtree',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/dhtmlxtree/dhtmlxtree.js',type:'js',charset:'utf-8',rely:['dhtmlxcommon','dhtmlxtreeCSS']});\r\n");
      out.write("\r\n");
      out.write("In.add('treeDialog',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/treeDialog.js',type:'js',charset:'utf-8'});\r\n");
      out.write("//jqtransform\r\n");
      out.write("In.add('jqtransformCSS',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jqtransform/jqtransformplugin/jqtransform.css',type:'css',charset:'utf-8'});\r\n");
      out.write("In.add('jqtransform',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jqtransform/jqtransformplugin/jquery.jqtransform.js',type:'js',charset:'utf-8',rely:['jqtransformCSS']});\r\n");
      out.write("//form\r\n");
      out.write("In.add('validTool',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/bootstrap/js/bootstrap.ccssoft.validTools.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('submit',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery.form.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('validate',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/validate.js',type:'js',charset:'utf-8',rely:['validTool','submit']});\r\n");
      out.write("\r\n");
      out.write("//others\r\n");
      out.write("In.add('frontierFloat',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/jquery.frontierFloat.js',type:'js',charset:'utf-8'});\r\n");
      out.write("In.add('confirm',{path:'");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/ui-confirm.js',type:'js',charset:'utf-8',rely:['frontierFloat']});\r\n");
      out.write("\r\n");
      out.write("var context = \"");
      out.print(getPath);
      out.write("\"\r\n");
      out.write("function showGlobalMessage(text,times,style){\r\n");
      out.write("\ttop.window.showTopMessage.show(text,times,style);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goTop() {\r\n");
      out.write("\t$('html, body').animate({ scrollTop: 0 }, 0);\r\n");
      out.write("}\r\n");
      out.write("var showDialog = top.window.bootDialog;\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(getPath);
      out.write("/baf/jsp/ui/js/topWindow.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/baf/jsp/uimain/home/style/page.css\">\r\n");
      out.write("<style>\r\n");
      out.write("html,body{height:100%;}\r\n");
      out.write(".toolbar{text-align:right;width:560px;}\r\n");
      out.write("body{padding-left:2em;}\r\n");
      out.write("\r\n");
      out.write(".menu a{text-decoration: none;}\r\n");
      out.write(".menu li{border:#fff 2px solid;}\r\n");
      out.write(".menu li:hover{border-color:#ccc;border-radius:6px;}\r\n");
      out.write(".menu li a{cursor:move;}\r\n");
      out.write(".menu li a.more{cursor:pointer;}\r\n");
      out.write(".menu li.empty:hover{border-color:#fff;}\r\n");
      out.write(".menu li.empty a{cursor:normal;}\r\n");
      out.write(".mask li{border:0;list-style:none;text-align:left;line-height:14px;}\r\n");
      out.write(".mask li .more{display:none;}\r\n");
      out.write(".menu li.sel{border:#fc0 2px solid;border-radius:6px;}\r\n");
      out.write(".TopModules li.dropbox{border-left:#ccc 2px solid;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onselectstart=\"return false\" style=\"-moz-user-select:none;\">\r\n");
      out.write("\t\t<div class=\"toolbar\">\r\n");
      out.write("\t\t\t<!--  <input type=\"text\" placeholder=\"输入关键字筛选模块\" />-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h3>导航栏上的模块</h3>\r\n");
      out.write("\t\t<ul class=\"menu TopModules\"></ul>\r\n");
      out.write("\t\t<h3>所有模块</h3>\r\n");
      out.write("\t\t<ul class=\"menu Modules\"></ul>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("document.oncontextmenu = document.onselectstart =  document.ondragstart = function(){\r\n");
      out.write("\treturn false;\r\n");
      out.write("}; \r\n");
      out.write("In.ready(\"underscore\",\"ccssoft\",\"dragable\",\"json\",function(){\r\n");
      out.write("\tvar TopModules = {\r\n");
      out.write("\t\tcount : 5,\r\n");
      out.write("\t\tdata : null,\r\n");
      out.write("\t\thandle  : $(\".TopModules\"),\r\n");
      out.write("\t\tposition : [],\r\n");
      out.write("\t\ttmpl : \"<li data-id='@{moduleId}' class='topModule'><a href='javascript:;'><span style='background-image:url(@{icon})'><span class='remove' title='从导航栏移除'></span></span>@{moduleName}</a></li>\",\r\n");
      out.write("\t\tdefaultIcon : \"/baf/jsp/uimain/home/style/images/icons/model.png\",\r\n");
      out.write("\t\tempt : \"<li class='empty'></li>\",\r\n");
      out.write("\t\tgetData : function(callback){\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(path);
      out.write("/uimain/getAllModuleByUser.do\";\r\n");
      out.write("\t\t\t$.getJSON(url,function(json){\r\n");
      out.write("\t\t\t\tt.data = _.sortBy(json.listTop,function(row){\r\n");
      out.write("\t\t\t\t\treturn row.sortOrder*1 || 99;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tcallback && callback();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsave : function(json){\r\n");
      out.write("\t\t\tvar m = Modules;\r\n");
      out.write("\t\t\tvar url=\"");
      out.print(path);
      out.write("/uimain/save.do?jsondata=\"+JSON.stringify(json);\r\n");
      out.write("\t\t\t$.getJSON(url,function(data){\r\n");
      out.write("\t\t\t\t//动态修改主页面的数据\r\n");
      out.write("\t\t\t\tif(data.state==\"1\"){\r\n");
      out.write("\t\t\t\t\tvar data = [];\r\n");
      out.write("\t\t\t\t\t_.each(json,function(row){\r\n");
      out.write("\t\t\t\t\t\tdata.push(m.getModuleById(row.moduleId));\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\ttop.window.menu.setView(data)\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tshowGlobalMessage(\"移动失败，请重新移动\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tinit : function(callback){\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\tt.getData(function(){\r\n");
      out.write("\t\t\t\tt.setView(t.data);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsetView : function(json){\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\tvar m = Modules;\r\n");
      out.write("\t\t\tvar view = [];\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < t.count ; i++){\r\n");
      out.write("\t\t\t\tvar row = json[i];\r\n");
      out.write("\t\t\t\tif(row){\r\n");
      out.write("\t\t\t\t\trow = m.getModuleById(row.moduleId);\r\n");
      out.write("\t\t\t\t\tview.push(ccssoft.stringReplace(t.tmpl,row));\r\n");
      out.write("\t\t\t\t}else\r\n");
      out.write("\t\t\t\t\tview.push(t.empt);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tt.handle.empty();\r\n");
      out.write("\t\t\tvar icons =  $(view.join(\"\")).appendTo(t.handle);\r\n");
      out.write("\t\t\ticons.each(function(i){\r\n");
      out.write("\t\t\t\tif(!json[i])json[i]={};\r\n");
      out.write("\t\t\t\tjson[i].top = $(this).offset().top;\r\n");
      out.write("\t\t\t\tjson[i].left = $(this).offset().left;\r\n");
      out.write("\t\t\t\tjson[i].height = this.offsetHeight;\r\n");
      out.write("\t\t\t\tjson[i].width = this.offsetWidth;\r\n");
      out.write("\t\t\t\tjson[i].handle = this;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tt.data = json;\r\n");
      out.write("\t\t\tdragEvents(icons);\r\n");
      out.write("\t\t\ticons.find(\".remove\").bind(\"mousedown\",function(ev){\r\n");
      out.write("\t\t\t\t(ev && ev.stopPropagation) ? ev.stopPropagation() : window.event.cancelBubble = true;\r\n");
      out.write("\t\t\t}).bind(\"click\",function(ev){\r\n");
      out.write("\t\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\t\tvar elemId = $(this).closest(\"li\").data(\"id\");\r\n");
      out.write("\t\t\t\tt.removeModule(elemId);\r\n");
      out.write("\t\t\t\t(ev && ev.stopPropagation) ? ev.stopPropagation() : window.event.cancelBubble = true;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn icons;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tremoveModule : function(id){\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\t//扁平化目标数组\r\n");
      out.write("\t\t\tvar arr = function(){\r\n");
      out.write("\t\t\t\tvar tmp = [];\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < t.data.length ; i++){\r\n");
      out.write("\t\t\t\t\tif(t.data[i].moduleId)tmp.push(t.data[i].moduleId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn tmp;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tarr = _.without(arr(),id);\r\n");
      out.write("\t\t\tvar returnJSON = [];\r\n");
      out.write("\t\t\tfor(var i  = 0 ; i < arr.length ; i++){\r\n");
      out.write("\t\t\t\treturnJSON.push({\r\n");
      out.write("\t\t\t\t\t\"moduleId\":arr[i],\r\n");
      out.write("\t\t\t\t\t\"sortOrder\":i+1\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tt.save(returnJSON);\r\n");
      out.write("\t\t\tt.setView(returnJSON);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tresetView : function(elemId,targetId){\r\n");
      out.write("\t\t\tif(targetId == elemId)return false;\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\t//扁平化目标数组\r\n");
      out.write("\t\t\tvar arr = function(){\r\n");
      out.write("\t\t\t\tvar tmp = [];\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < t.data.length ; i++){\r\n");
      out.write("\t\t\t\t\tif(t.data[i].moduleId)tmp.push(t.data[i].moduleId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn tmp;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tarr = _.without(arr(),elemId);\r\n");
      out.write("\t\t\tif(targetId){\r\n");
      out.write("\t\t\t\tvar arrTmp = [];\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < arr.length ; i++){\r\n");
      out.write("\t\t\t\t\tif(targetId === arr[i])arrTmp.push(elemId);\r\n");
      out.write("\t\t\t\t\tarrTmp.push(arr[i]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tarr = arrTmp ;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tarr.push(elemId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(arr.length > t.count){\r\n");
      out.write("\t\t\t\tshowGlobalMessage(\"导航栏模块已满，请删除一个再进行添加\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar returnJSON = [];\r\n");
      out.write("\t\t\tfor(var i  = 0 ; i < arr.length ; i++){\r\n");
      out.write("\t\t\t\treturnJSON.push({\r\n");
      out.write("\t\t\t\t\t\"moduleId\":arr[i],\r\n");
      out.write("\t\t\t\t\t\"sortOrder\":i+1\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tt.save(returnJSON);\r\n");
      out.write("\t\t\tt.setView(returnJSON);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tvar Modules = {\r\n");
      out.write("\t\tdata : null,\r\n");
      out.write("\t\thandle : $(\".Modules\"),\r\n");
      out.write("\t\ttmpl : \"<li data-id='@{moduleId}' class='module'><a href='javascript:;'><span style='background-image:url(@{icon})'><span class='add' title='添加到导航栏'></span></span>@{moduleName}</a><a class='more' href='@{moduleUrl}'>进入模块</a></li>\",\r\n");
      out.write("\t\tdefaultIcon : \"/baf/jsp/uimain/home/style/images/icons/model.png\",\r\n");
      out.write("\t\tgetData : function(callback){\r\n");
      out.write("\t\t\tvar m = Modules;\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(path);
      out.write("/uimain/getAllModuleByUser.do\";\r\n");
      out.write("\t\t\t$.getJSON(url,function(json){\r\n");
      out.write("\t\t\t\tm.data = json.listMore;\r\n");
      out.write("\t\t\t\tcallback && callback();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tinit : function(callback){\r\n");
      out.write("\t\t\tvar m = Modules;\r\n");
      out.write("\t\t\tm.getData(function(){\r\n");
      out.write("\t\t\t\tvar view = [];\r\n");
      out.write("\t\t\t\t_.each(m.data,function(row){\r\n");
      out.write("\t\t\t\t\trow.icon = row.largeIcon || m.defaultIcon;\r\n");
      out.write("\t\t\t\t\tif(row.applicationId && row.applicationId !=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationId}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" && row.moduleUrl){\r\n");
      out.write("\t\t\t\t\t\tif(row.moduleUrl.indexOf(\"?\") == -1)\r\n");
      out.write("\t\t\t\t\t\t\trow.moduleUrl = row.moduleUrl + \"?operID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("&hashCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${thisHashCode}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\trow.moduleUrl = row.moduleUrl + \"&operID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("&hashCode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${thisHashCode}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}else if(!row.applicationId && row.moduleUrl){\r\n");
      out.write("\t\t\t\t\t\t\trow.moduleUrl = row.moduleUrl + \"?id=\"+row.moduleId+\"&img=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/\"+row.largeIcon+\"&moduleName=\"+row.simpleName;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\trow.moduleUrl = \"/baf/jsp/uimain/home/frame.jsp?id=\"+row.moduleId+\"&img=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/\"+row.largeIcon+\"&moduleName=\"+row.simpleName;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tview.push(ccssoft.stringReplace(m.tmpl,row));\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tvar icons = $(view.join(\"\")).appendTo(m.handle);\r\n");
      out.write("\t\t\t\tdragEvents(icons);\r\n");
      out.write("\t\t\t\tcallback && callback();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tgetModuleById : function(moduleId){\r\n");
      out.write("\t\t\tvar m = Modules;\r\n");
      out.write("\t\t\tvar row =  _.where(m.data,{moduleId:moduleId})[0];\r\n");
      out.write("\t\t\treturn row;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tModules.init(function(){\r\n");
      out.write("\t\tTopModules.init();\r\n");
      out.write("\t});\r\n");
      out.write("\tvar dragEvents = function(elems){\r\n");
      out.write("\t\tvar setting = {\r\n");
      out.write("\t\t\tondragstart : function(elem,mask,ev){\r\n");
      out.write("\t\t\t\tmask.empty().append(elem.clone()).addClass(\"menu\").find(\".more\").remove();;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tondrag : function(elem,mask,ev){\r\n");
      out.write("\t\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\t\tvar point = {\r\n");
      out.write("\t\t\t\t\ttop : ev.pageY,\r\n");
      out.write("\t\t\t\t\tleft : ev.pageX\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t_.each(t.data,function(row){\r\n");
      out.write("\t\t\t\t\tif(inArea(point,row)){\r\n");
      out.write("\t\t\t\t\t\t$(row.handle).addClass(\"dropbox\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(row.handle).removeClass(\"dropbox\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tondragend : function(elem,mask,ev){\r\n");
      out.write("\t\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\t\tvar elemId = $(elem).data(\"id\");\r\n");
      out.write("\t\t\t\tvar targetId = $(\".dropbox\").data(\"id\");\r\n");
      out.write("\t\t\t\tif($(\".dropbox\").length !== 1){\r\n");
      out.write("\t\t\t\t\tif(elemId && $(elem).hasClass(\"topModule\")){\r\n");
      out.write("\t\t\t\t\t\tt.removeModule($(elem).data(\"id\"));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\".dropbox\").removeClass(\"dropbox\");\r\n");
      out.write("\t\t\t\tif($(elem).hasClass(\"module\")){\r\n");
      out.write("\t\t\t\t\tvar module = _.find(t.data,function(row){\r\n");
      out.write("\t\t\t\t\t\treturn row.moduleId == elemId;\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\tif(module){\r\n");
      out.write("\t\t\t\t\t\t$(module.handle).addClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(module.handle).removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\t},1000);\r\n");
      out.write("\t\t\t\t\t\t//showGlobalMessage(\"此模块已经在导航栏上了\");\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tt.resetView(elemId,targetId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\telems.each(function(){\r\n");
      out.write("\t\t\tif($(this).hasClass(\"empty\"))return false;\r\n");
      out.write("\t\t\t$(this).dragable(setting);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\telems.find(\".more\").bind(\"mousedown\",function(ev){\r\n");
      out.write("\t\t\t(ev && ev.stopPropagation) ? ev.stopPropagation() : window.event.cancelBubble = true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\telems.find(\".add\").bind(\"mousedown\",function(ev){\r\n");
      out.write("\t\t\t(ev && ev.stopPropagation) ? ev.stopPropagation() : window.event.cancelBubble = true;\r\n");
      out.write("\t\t}).bind(\"click\",function(ev){\r\n");
      out.write("\t\t\tvar t = TopModules;\r\n");
      out.write("\t\t\tvar elem = $(this).closest(\"li\")\r\n");
      out.write("\t\t\tvar elemId = elem.data(\"id\");\r\n");
      out.write("\t\t\tif($(elem).hasClass(\"module\")){\r\n");
      out.write("\t\t\t\tvar module = _.find(t.data,function(row){\r\n");
      out.write("\t\t\t\t\treturn row.moduleId == elemId;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tif(module){\r\n");
      out.write("\t\t\t\t\t$(module.handle).addClass(\"sel\");\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t$(module.handle).removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t},1000);\r\n");
      out.write("\t\t\t\t\t//showGlobalMessage(\"此模块已经在导航栏上了\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tt.resetView(elemId,\"\");\r\n");
      out.write("\t\t\t(ev && ev.stopPropagation) ? ev.stopPropagation() : window.event.cancelBubble = true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar inArea = function(point,area){\r\n");
      out.write("\t\tvar xArea = false;\r\n");
      out.write("\t\tvar yArea = false;\r\n");
      out.write("\t\tif(area.left < point.left && (area.left+area.width) > point.left)xArea = true;\r\n");
      out.write("\t\tif(area.top < point.top && (area.top+area.height) > point.top)yArea = true;\r\n");
      out.write("\t\tif(xArea && yArea)\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
