package org.apache.jsp.baf.jsp.uimain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.regaltec.baf.org.user.common.valueobj.UserVO;
import com.regaltec.baf.org.user.ui.control.UserLoginBean;
import java.util.Locale;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html> \r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/ui/js/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/ui/js/bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link type='text/css' rel='stylesheet' href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/home.css' />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/ui/js/jquery-1.7.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/js/jq.Slide.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/js/jquery.frontierFloat.js\"></script>\r\n");
      out.write("    <title>移动应用服务平台</title>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \ta.super{\r\n");
      out.write("    \t\tcolor:#444;\r\n");
      out.write("    \t\tfont-weight:bold;\r\n");
      out.write("    \t\tfloat:right;\r\n");
      out.write("    \t\twidth:191px;\r\n");
      out.write("    \t\theight:24px;\r\n");
      out.write("    \t\tline-height:24px;\r\n");
      out.write("    \t\ttext-align:center;\r\n");
      out.write("    \t\tmargin-right:20px;\r\n");
      out.write("    \t\tbackground:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/images/roll.png) 0 0 no-repeat;\r\n");
      out.write("    \t}\r\n");
      out.write("    \ta.super:hover{\r\n");
      out.write("    \t\ttext-decoration: none;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a class=\"super\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/handBook/queryAll.p\" target=\"_handbook\">帮助中心</a>\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<ul class=\"appList\">\r\n");
      out.write("\t\t\t\t<li class=\"appTitle\"></li>\r\n");
      out.write("\t\t\t\t<li class=\"android\" data-qr=\"/fileServer/QRCode/android.png\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/hallVersion/download.p?os=android\">Android下载</a><span class=\"dropdown\"><i class=\"caret\"></i></span></li>\r\n");
      out.write("\t\t\t\t<li class=\"ios\" data-qr=\"/fileServer/QRCode/ios.png\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/hallVersion/download.p?os=ios\">iOS下载</a><span class=\"dropdown\"><i class=\"caret\"></i></span></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<h1>中国电信移动应用服务平台</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"slider\" id=\"slider\">\r\n");
      out.write("\t\t<div class=\"JQ-content-box\" >\r\n");
      out.write("\t\t  <ul class=\"JQ-slide-content\">\r\n");
      out.write("\t\t\t<li style=\"background:#3ea288 url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/slider/3.jpg) repeat-x 50% 50%;\"></li>\r\n");
      out.write("\t\t\t<li style=\"background:#0087c1 url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/slider/2.jpg) repeat-x 50% 50%;\"></li>\r\n");
      out.write("\t\t\t<li style=\"background:#6e792e url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/slider/1.jpg) repeat-x 50% 50%;\"></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t  <ul class=\"JQ-slide-nav\">\r\n");
      out.write("\t\t\t<li class=\"on\"></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container container-fluid loginForm\">\r\n");
      out.write("\t\t<div class=\"body\">\r\n");
      out.write("\t\t\t<form name=\"loginForm\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t<div class=\"box_inner\">\r\n");
      out.write("\t\t\t\t\t<h4>用户登录：</h4>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"text loginName opacity80\" type=\"text\" name=\"loginName\" placeholder=\"输入用户名\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"text passwd opacity80\" type=\"password\" name=\"password\" placeholder=\"输入密码\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"validCode\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"text validCode opacity80\" type=\"text\" name=\"validateCode\" maxlength=\"4\" placeholder=\"验证码\" />\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"看不清？点击换一张 \" class=\"opacity80 resetValidCode\"><img class=\"validCodeImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/servlet/ValidateCodeServlet\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"action\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-block btn-large btn-primary submit\" type=\"button\">登 录</button>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" class=\"sendPw\">忘记了密码？点此找回</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert hide\" style=\"margin-top: 20px;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"info clearfix\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/images/icons/1.png\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<h4>统一的应用管理</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>提供移动应用管理与运行控制，实现对终端移动应用的发布、使用、监测和优化的生命周期管理，实现对移动应用的统一管理，建立使用者和应用发布者的沟通渠道。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/images/icons/2.png\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<h4>标准架构</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>建立“应用+平台”标准架构，为移动应用提供统一的运行环镜，简化后端的集成, 提供单一的管理平台，集中管理、保护和部署移动应用。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/images/icons/3.png\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<h4>让应用开发更简单</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>一站式的移动应用开发平台可以简单、快速、高效地创建Android、iPhone等多种终端操作系统的移动应用，解决移动应用开发门槛高、平台适配难、开发周期长等问题。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t<img class=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uimain/home/style/images/icons/4.png\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<h4>多手段的管理支撑</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>将不同的移动应用进行整合，形成综合化的移动应用；实现综合化的移动信息应用，融合各业务系统能力、数据，多应用集成实现丰富业务移动支撑能力。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer clearfix\"> \r\n");
      out.write("\t\t<p>copyright &copy; 2013 <a href=\"http://www.ccssoft.com.cn\">CCSSOFT Corporation</a>, All Rights Reserved</p>\r\n");
      out.write("\t\t<p>增值电信业务经营许可证 A2.B1.B2-20090001</p>\r\n");
      out.write("\t\t<p>文网文(2008)053号 </p>\r\n");
      out.write("\t\t<p>ICP证号：京ICP备09031924号</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t~function(){\r\n");
      out.write("\t\t$(\"[name=loginName]\").focus();\r\n");
      out.write("\t\t$(\"#slider\").Slide({\r\n");
      out.write("\t\t\teffect : \"fade\",\r\n");
      out.write("\t\t\tspeed : \"normal\",\r\n");
      out.write("\t\t\tautoPlay : true,\r\n");
      out.write("\t\t\ttimer : 5000\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".appList\").delegate(\"li\",\"mouseover\",function(){\r\n");
      out.write("\t\t\tvar qr = $(this).attr(\"data-qr\");\r\n");
      out.write("\t\t\tif(!qr)return false;\r\n");
      out.write("\t\t\tvar html = \"<div class='arrow shadow' style='margin:0;width:150px;'><h4>拍摄二维码</h4><p style='text-align:center;background:#000 url(\"+qr+\") center no-repeat;width:120px;height:120px;margin:0 0 0 14px;'></p><p class='muted'>使用手机上的二维码扫描软件拍摄以上二维码即可立即下载。</p></div>\"\r\n");
      out.write("\t\t\t$(this).frontierFloat({\r\n");
      out.write("\t\t\t\ttext : html,\r\n");
      out.write("\t\t\t\tfloat: {x:0,y:5}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction validate(data){\r\n");
      out.write("\t\t\tvar sign = true;\r\n");
      out.write("\t\t\t$(\"input.error\").removeClass(\"error\");\r\n");
      out.write("\t\t\tfor(var k in data){\r\n");
      out.write("\t\t\t\tif(!data[k]){\r\n");
      out.write("\t\t\t\t\tsign = false;\r\n");
      out.write("\t\t\t\t\t$(\"[name=\"+k+\"]\").focus().addClass(\"error\");\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn sign;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction sendPw(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/baf/jsp/uiframe/forgetPassword.xhtml\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction resetValidCode(){\r\n");
      out.write("\t\t\tvar timer = new Date().getTime();                        \r\n");
      out.write("\t\t\t$(\".validCodeImg\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/servlet/ValidateCodeServlet?d=\"+timer);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction resetForm(){\r\n");
      out.write("\t\t\t$(\"[name=password]\").val(\"\");\r\n");
      out.write("\t\t\t$(\"[name=validateCode]\").val(\"\");\r\n");
      out.write("\t\t\tresetValidCode();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction submit(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//判断安全策略是否打开\r\n");
      out.write("\t\t\t$.ajax({  \r\n");
      out.write("                async:false,//使用同步的Ajax请求  \r\n");
      out.write("                type: \"POST\",  \r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/uimain/isSafeCheck.do\",  \r\n");
      out.write("                data: \"\",  \r\n");
      out.write("                success: function(data){\r\n");
      out.write("                \tif(\"1\"==data){\r\n");
      out.write("                \t\tdesPsw();\r\n");
      out.write("                \t}  \r\n");
      out.write("                }  \r\n");
      out.write("           });  \r\n");
      out.write("\t\t\tvar data = $(\"[name=loginForm]\").serialize();\r\n");
      out.write("\t\t\tdata = serialize2json(data);\r\n");
      out.write("\t\t\tif(!validate(data))return false;\r\n");
      out.write("\t\t\tvar button = $(\".submit\");\r\n");
      out.write("\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/checkLogin.do\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tbutton.attr(\"disabled\",true).addClass(\"disabled\");\r\n");
      out.write("\t\t\t$.post(url,data,function(state){\r\n");
      out.write("\t\t\t\tvar data=state.status;\r\n");
      out.write("\t\t\t\tvar status = {\r\n");
      out.write("\t\t\t\t\t\"-2\" : \"登录失败，密码错误！\",\r\n");
      out.write("\t\t\t\t\t\"-1\" : \"登录失败，账号不存在！\",\r\n");
      out.write("\t\t\t\t\t1  : \"OK\",\r\n");
      out.write("\t\t\t\t\t2  : \"您的密码已到期，请修改密码！\",\r\n");
      out.write("\t\t\t\t\t3  : \"验证码输入错误！\",\r\n");
      out.write("\t\t\t\t\t4  : \"强制修改密码\",\r\n");
      out.write("\t\t\t\t\t51 : \"登录失败！系统要求绑定IP地址登录，请绑定IP地址！\",\r\n");
      out.write("\t\t\t\t\t52 : \"登录失败！您的登录IP与您绑定的IP不符！\",\r\n");
      out.write("\t\t\t\t\t6  : \"动态密码不正确，请点击获取!\",\r\n");
      out.write("\t\t\t\t\t7  : \"动态密码不正确，请重新输入!\",\r\n");
      out.write("\t\t\t\t\t8  : \"当前人员必须通过统一认证系统登录！\",\r\n");
      out.write("\t\t\t\t\t9  : \"有多个部门需选择一个\",\r\n");
      out.write("\t\t\t\t\t10 : \"您已经被选为试运行发布测试用户，系统将自动跳转到试运行服务器，请重新输入密码登录!\",\r\n");
      out.write("\t\t\t\t\t11 : \"密码不能再错一次，否则被锁定!\",\r\n");
      out.write("\t\t\t\t\t12 : \"密码错误次数\"+state.sysCount+\"次被锁!解锁请联系管理员！\",\r\n");
      out.write("\t\t\t\t\t13 : \"您登陆的IP地址已经被限制登陆，请联系管理员解除限制！\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\t\tvar action = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(status[data]){\r\n");
      out.write("\t\t\t\t\tif(data == 1)\r\n");
      out.write("\t\t\t\t\t\taction = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index.do\";\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\tmsg = status[data];\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(data.indexOf(\"#\")!= -1){\r\n");
      out.write("\t\t\t\t\t\tvar state = data.split(\"#\")[0];\r\n");
      out.write("\t\t\t\t\t\tvar message = data.split(\"#\")[1];\r\n");
      out.write("\t\t\t\t\t\tif(state == 5){\r\n");
      out.write("\t\t\t\t\t\t\tif(!message)\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg = status[51];\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg = status[52];\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(state == 10){\r\n");
      out.write("\t\t\t\t\t\t\tmsg = status[10];\r\n");
      out.write("\t\t\t\t\t\t\taction = \"http://\"+message;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(state == 11 || state == 12)\r\n");
      out.write("\t\t\t\t\t\t\tmsg = message;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"出现未知错误无法处理\");\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(msg){\r\n");
      out.write("\t\t\t\t\t$(\".login_box .action\").hide();\r\n");
      out.write("\t\t\t\t\t$(\".login_box .alert\").show().html(msg);\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".login_box .alert\").slideUp(\"normal\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".login_box .action\").show();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t},2000);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tbutton.attr(\"disabled\",false).removeClass(\"disabled\");\r\n");
      out.write("\t\t\t\tif(action)location.href=action;\r\n");
      out.write("\t\t\t\tresetForm();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction serialize2json(serial){\r\n");
      out.write("\t\t\tserial = decodeURIComponent(serial);\r\n");
      out.write("\t\t\tvar arr = serial.split(\"&\");\r\n");
      out.write("\t\t\tvar result = {};\r\n");
      out.write("\t\t\tfor(var i = 0, row ; row = arr[i] ; i++){\r\n");
      out.write("\t\t\t\tvar member = row.split(\"=\");\r\n");
      out.write("\t\t\t\tresult[member[0]] = member[1];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn result;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"body\")\r\n");
      out.write("\t\t\t.delegate(\".sendPw\",\"click\",sendPw)\r\n");
      out.write("\t\t\t.delegate(\".resetValidCode\",\"click\",resetValidCode)\r\n");
      out.write("\t\t\t.delegate(\".submit\",\"click\",submit)\r\n");
      out.write("\t\t\t.bind(\"keydown\",function(event){\r\n");
      out.write("\t\t\t\tif(event.keyCode == 13)submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}();\r\n");
      out.write("\t\r\n");
      out.write("\t//密码加密\r\n");
      out.write("\tfunction desPsw(){\r\n");
      out.write("\t\tvar password=$(\"[name=password]\").val();\r\n");
      out.write("   \t    $(\"[name=password]\").val(encode(password));  \r\n");
      out.write("   \t }\r\n");
      out.write("   \t \r\n");
      out.write("   \t function encode(value) {\r\n");
      out.write("\t    var key = '密'.charCodeAt(0);\r\n");
      out.write("\t    var str = \"\";\r\n");
      out.write("\t    for(var i=0;i<value.length;i++) {\r\n");
      out.write("\t     str += value.charCodeAt(i)^key;\r\n");
      out.write("\t     if (i<value.length-1) {\r\n");
      out.write("\t      str +=\"%\";\r\n");
      out.write("\t     }\r\n");
      out.write("\t    }\r\n");
      out.write("\t    return str;\r\n");
      out.write("   }\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
