package com.ccssoft.rsas.pwb.user.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BafOrgUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public BafOrgUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUseridIsNull() {
			addCriterion("USERID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("USERID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("USERID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("USERID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("USERID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("USERID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("USERID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("USERID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("USERID like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("USERID not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("USERID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("USERID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("USERID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("USERID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNull() {
			addCriterion("USERTYPE is null");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNotNull() {
			addCriterion("USERTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andUsertypeEqualTo(String value) {
			addCriterion("USERTYPE =", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotEqualTo(String value) {
			addCriterion("USERTYPE <>", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThan(String value) {
			addCriterion("USERTYPE >", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThanOrEqualTo(String value) {
			addCriterion("USERTYPE >=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThan(String value) {
			addCriterion("USERTYPE <", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThanOrEqualTo(String value) {
			addCriterion("USERTYPE <=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLike(String value) {
			addCriterion("USERTYPE like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotLike(String value) {
			addCriterion("USERTYPE not like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeIn(List<String> values) {
			addCriterion("USERTYPE in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotIn(List<String> values) {
			addCriterion("USERTYPE not in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeBetween(String value1, String value2) {
			addCriterion("USERTYPE between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotBetween(String value1, String value2) {
			addCriterion("USERTYPE not between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andLoginnameIsNull() {
			addCriterion("LOGINNAME is null");
			return (Criteria) this;
		}

		public Criteria andLoginnameIsNotNull() {
			addCriterion("LOGINNAME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginnameEqualTo(String value) {
			addCriterion("LOGINNAME =", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotEqualTo(String value) {
			addCriterion("LOGINNAME <>", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameGreaterThan(String value) {
			addCriterion("LOGINNAME >", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGINNAME >=", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLessThan(String value) {
			addCriterion("LOGINNAME <", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLessThanOrEqualTo(String value) {
			addCriterion("LOGINNAME <=", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameLike(String value) {
			addCriterion("LOGINNAME like", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotLike(String value) {
			addCriterion("LOGINNAME not like", value, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameIn(List<String> values) {
			addCriterion("LOGINNAME in", values, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotIn(List<String> values) {
			addCriterion("LOGINNAME not in", values, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameBetween(String value1, String value2) {
			addCriterion("LOGINNAME between", value1, value2, "loginname");
			return (Criteria) this;
		}

		public Criteria andLoginnameNotBetween(String value1, String value2) {
			addCriterion("LOGINNAME not between", value1, value2, "loginname");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("USERNAME is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("USERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("USERNAME =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("USERNAME <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("USERNAME >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("USERNAME >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("USERNAME <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("USERNAME <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("USERNAME like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("USERNAME not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("USERNAME in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("USERNAME not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("USERNAME between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("USERNAME not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("GENDER is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("GENDER is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("GENDER =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("GENDER <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("GENDER >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("GENDER >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("GENDER <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("GENDER <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("GENDER like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("GENDER not like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<String> values) {
			addCriterion("GENDER in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<String> values) {
			addCriterion("GENDER not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("GENDER between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("GENDER not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andEmploydateIsNull() {
			addCriterion("EMPLOYDATE is null");
			return (Criteria) this;
		}

		public Criteria andEmploydateIsNotNull() {
			addCriterion("EMPLOYDATE is not null");
			return (Criteria) this;
		}

		public Criteria andEmploydateEqualTo(Date value) {
			addCriterion("EMPLOYDATE =", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateNotEqualTo(Date value) {
			addCriterion("EMPLOYDATE <>", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateGreaterThan(Date value) {
			addCriterion("EMPLOYDATE >", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateGreaterThanOrEqualTo(Date value) {
			addCriterion("EMPLOYDATE >=", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateLessThan(Date value) {
			addCriterion("EMPLOYDATE <", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateLessThanOrEqualTo(Date value) {
			addCriterion("EMPLOYDATE <=", value, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateIn(List<Date> values) {
			addCriterion("EMPLOYDATE in", values, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateNotIn(List<Date> values) {
			addCriterion("EMPLOYDATE not in", values, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateBetween(Date value1, Date value2) {
			addCriterion("EMPLOYDATE between", value1, value2, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmploydateNotBetween(Date value1, Date value2) {
			addCriterion("EMPLOYDATE not between", value1, value2, "employdate");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andOfficephoneIsNull() {
			addCriterion("OFFICEPHONE is null");
			return (Criteria) this;
		}

		public Criteria andOfficephoneIsNotNull() {
			addCriterion("OFFICEPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andOfficephoneEqualTo(String value) {
			addCriterion("OFFICEPHONE =", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneNotEqualTo(String value) {
			addCriterion("OFFICEPHONE <>", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneGreaterThan(String value) {
			addCriterion("OFFICEPHONE >", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneGreaterThanOrEqualTo(String value) {
			addCriterion("OFFICEPHONE >=", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneLessThan(String value) {
			addCriterion("OFFICEPHONE <", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneLessThanOrEqualTo(String value) {
			addCriterion("OFFICEPHONE <=", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneLike(String value) {
			addCriterion("OFFICEPHONE like", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneNotLike(String value) {
			addCriterion("OFFICEPHONE not like", value, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneIn(List<String> values) {
			addCriterion("OFFICEPHONE in", values, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneNotIn(List<String> values) {
			addCriterion("OFFICEPHONE not in", values, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneBetween(String value1, String value2) {
			addCriterion("OFFICEPHONE between", value1, value2, "officephone");
			return (Criteria) this;
		}

		public Criteria andOfficephoneNotBetween(String value1, String value2) {
			addCriterion("OFFICEPHONE not between", value1, value2, "officephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneIsNull() {
			addCriterion("HOMEPHONE is null");
			return (Criteria) this;
		}

		public Criteria andHomephoneIsNotNull() {
			addCriterion("HOMEPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andHomephoneEqualTo(String value) {
			addCriterion("HOMEPHONE =", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneNotEqualTo(String value) {
			addCriterion("HOMEPHONE <>", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneGreaterThan(String value) {
			addCriterion("HOMEPHONE >", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneGreaterThanOrEqualTo(String value) {
			addCriterion("HOMEPHONE >=", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneLessThan(String value) {
			addCriterion("HOMEPHONE <", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneLessThanOrEqualTo(String value) {
			addCriterion("HOMEPHONE <=", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneLike(String value) {
			addCriterion("HOMEPHONE like", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneNotLike(String value) {
			addCriterion("HOMEPHONE not like", value, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneIn(List<String> values) {
			addCriterion("HOMEPHONE in", values, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneNotIn(List<String> values) {
			addCriterion("HOMEPHONE not in", values, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneBetween(String value1, String value2) {
			addCriterion("HOMEPHONE between", value1, value2, "homephone");
			return (Criteria) this;
		}

		public Criteria andHomephoneNotBetween(String value1, String value2) {
			addCriterion("HOMEPHONE not between", value1, value2, "homephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIsNull() {
			addCriterion("MOBILEPHONE is null");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIsNotNull() {
			addCriterion("MOBILEPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andMobilephoneEqualTo(String value) {
			addCriterion("MOBILEPHONE =", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotEqualTo(String value) {
			addCriterion("MOBILEPHONE <>", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneGreaterThan(String value) {
			addCriterion("MOBILEPHONE >", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILEPHONE >=", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLessThan(String value) {
			addCriterion("MOBILEPHONE <", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLessThanOrEqualTo(String value) {
			addCriterion("MOBILEPHONE <=", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLike(String value) {
			addCriterion("MOBILEPHONE like", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotLike(String value) {
			addCriterion("MOBILEPHONE not like", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIn(List<String> values) {
			addCriterion("MOBILEPHONE in", values, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotIn(List<String> values) {
			addCriterion("MOBILEPHONE not in", values, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneBetween(String value1, String value2) {
			addCriterion("MOBILEPHONE between", value1, value2, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotBetween(String value1, String value2) {
			addCriterion("MOBILEPHONE not between", value1, value2, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andPhsIsNull() {
			addCriterion("PHS is null");
			return (Criteria) this;
		}

		public Criteria andPhsIsNotNull() {
			addCriterion("PHS is not null");
			return (Criteria) this;
		}

		public Criteria andPhsEqualTo(String value) {
			addCriterion("PHS =", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsNotEqualTo(String value) {
			addCriterion("PHS <>", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsGreaterThan(String value) {
			addCriterion("PHS >", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsGreaterThanOrEqualTo(String value) {
			addCriterion("PHS >=", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsLessThan(String value) {
			addCriterion("PHS <", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsLessThanOrEqualTo(String value) {
			addCriterion("PHS <=", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsLike(String value) {
			addCriterion("PHS like", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsNotLike(String value) {
			addCriterion("PHS not like", value, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsIn(List<String> values) {
			addCriterion("PHS in", values, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsNotIn(List<String> values) {
			addCriterion("PHS not in", values, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsBetween(String value1, String value2) {
			addCriterion("PHS between", value1, value2, "phs");
			return (Criteria) this;
		}

		public Criteria andPhsNotBetween(String value1, String value2) {
			addCriterion("PHS not between", value1, value2, "phs");
			return (Criteria) this;
		}

		public Criteria andPagerIsNull() {
			addCriterion("PAGER is null");
			return (Criteria) this;
		}

		public Criteria andPagerIsNotNull() {
			addCriterion("PAGER is not null");
			return (Criteria) this;
		}

		public Criteria andPagerEqualTo(String value) {
			addCriterion("PAGER =", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerNotEqualTo(String value) {
			addCriterion("PAGER <>", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerGreaterThan(String value) {
			addCriterion("PAGER >", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerGreaterThanOrEqualTo(String value) {
			addCriterion("PAGER >=", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerLessThan(String value) {
			addCriterion("PAGER <", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerLessThanOrEqualTo(String value) {
			addCriterion("PAGER <=", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerLike(String value) {
			addCriterion("PAGER like", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerNotLike(String value) {
			addCriterion("PAGER not like", value, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerIn(List<String> values) {
			addCriterion("PAGER in", values, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerNotIn(List<String> values) {
			addCriterion("PAGER not in", values, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerBetween(String value1, String value2) {
			addCriterion("PAGER between", value1, value2, "pager");
			return (Criteria) this;
		}

		public Criteria andPagerNotBetween(String value1, String value2) {
			addCriterion("PAGER not between", value1, value2, "pager");
			return (Criteria) this;
		}

		public Criteria andFaxIsNull() {
			addCriterion("FAX is null");
			return (Criteria) this;
		}

		public Criteria andFaxIsNotNull() {
			addCriterion("FAX is not null");
			return (Criteria) this;
		}

		public Criteria andFaxEqualTo(String value) {
			addCriterion("FAX =", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotEqualTo(String value) {
			addCriterion("FAX <>", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThan(String value) {
			addCriterion("FAX >", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThanOrEqualTo(String value) {
			addCriterion("FAX >=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThan(String value) {
			addCriterion("FAX <", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThanOrEqualTo(String value) {
			addCriterion("FAX <=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLike(String value) {
			addCriterion("FAX like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotLike(String value) {
			addCriterion("FAX not like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxIn(List<String> values) {
			addCriterion("FAX in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotIn(List<String> values) {
			addCriterion("FAX not in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxBetween(String value1, String value2) {
			addCriterion("FAX between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotBetween(String value1, String value2) {
			addCriterion("FAX not between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andIsvalidIsNull() {
			addCriterion("ISVALID is null");
			return (Criteria) this;
		}

		public Criteria andIsvalidIsNotNull() {
			addCriterion("ISVALID is not null");
			return (Criteria) this;
		}

		public Criteria andIsvalidEqualTo(String value) {
			addCriterion("ISVALID =", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidNotEqualTo(String value) {
			addCriterion("ISVALID <>", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidGreaterThan(String value) {
			addCriterion("ISVALID >", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidGreaterThanOrEqualTo(String value) {
			addCriterion("ISVALID >=", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidLessThan(String value) {
			addCriterion("ISVALID <", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidLessThanOrEqualTo(String value) {
			addCriterion("ISVALID <=", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidLike(String value) {
			addCriterion("ISVALID like", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidNotLike(String value) {
			addCriterion("ISVALID not like", value, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidIn(List<String> values) {
			addCriterion("ISVALID in", values, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidNotIn(List<String> values) {
			addCriterion("ISVALID not in", values, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidBetween(String value1, String value2) {
			addCriterion("ISVALID between", value1, value2, "isvalid");
			return (Criteria) this;
		}

		public Criteria andIsvalidNotBetween(String value1, String value2) {
			addCriterion("ISVALID not between", value1, value2, "isvalid");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andLimitedipIsNull() {
			addCriterion("LIMITEDIP is null");
			return (Criteria) this;
		}

		public Criteria andLimitedipIsNotNull() {
			addCriterion("LIMITEDIP is not null");
			return (Criteria) this;
		}

		public Criteria andLimitedipEqualTo(String value) {
			addCriterion("LIMITEDIP =", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipNotEqualTo(String value) {
			addCriterion("LIMITEDIP <>", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipGreaterThan(String value) {
			addCriterion("LIMITEDIP >", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipGreaterThanOrEqualTo(String value) {
			addCriterion("LIMITEDIP >=", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipLessThan(String value) {
			addCriterion("LIMITEDIP <", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipLessThanOrEqualTo(String value) {
			addCriterion("LIMITEDIP <=", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipLike(String value) {
			addCriterion("LIMITEDIP like", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipNotLike(String value) {
			addCriterion("LIMITEDIP not like", value, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipIn(List<String> values) {
			addCriterion("LIMITEDIP in", values, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipNotIn(List<String> values) {
			addCriterion("LIMITEDIP not in", values, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipBetween(String value1, String value2) {
			addCriterion("LIMITEDIP between", value1, value2, "limitedip");
			return (Criteria) this;
		}

		public Criteria andLimitedipNotBetween(String value1, String value2) {
			addCriterion("LIMITEDIP not between", value1, value2, "limitedip");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("CREATEDATE =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("CREATEDATE <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("CREATEDATE >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("CREATEDATE <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("CREATEDATE in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("CREATEDATE not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andExpireddateIsNull() {
			addCriterion("EXPIREDDATE is null");
			return (Criteria) this;
		}

		public Criteria andExpireddateIsNotNull() {
			addCriterion("EXPIREDDATE is not null");
			return (Criteria) this;
		}

		public Criteria andExpireddateEqualTo(Date value) {
			addCriterion("EXPIREDDATE =", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateNotEqualTo(Date value) {
			addCriterion("EXPIREDDATE <>", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateGreaterThan(Date value) {
			addCriterion("EXPIREDDATE >", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateGreaterThanOrEqualTo(Date value) {
			addCriterion("EXPIREDDATE >=", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateLessThan(Date value) {
			addCriterion("EXPIREDDATE <", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateLessThanOrEqualTo(Date value) {
			addCriterion("EXPIREDDATE <=", value, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateIn(List<Date> values) {
			addCriterion("EXPIREDDATE in", values, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateNotIn(List<Date> values) {
			addCriterion("EXPIREDDATE not in", values, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateBetween(Date value1, Date value2) {
			addCriterion("EXPIREDDATE between", value1, value2, "expireddate");
			return (Criteria) this;
		}

		public Criteria andExpireddateNotBetween(Date value1, Date value2) {
			addCriterion("EXPIREDDATE not between", value1, value2, "expireddate");
			return (Criteria) this;
		}

		public Criteria andCreatoridIsNull() {
			addCriterion("CREATORID is null");
			return (Criteria) this;
		}

		public Criteria andCreatoridIsNotNull() {
			addCriterion("CREATORID is not null");
			return (Criteria) this;
		}

		public Criteria andCreatoridEqualTo(String value) {
			addCriterion("CREATORID =", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridNotEqualTo(String value) {
			addCriterion("CREATORID <>", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridGreaterThan(String value) {
			addCriterion("CREATORID >", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
			addCriterion("CREATORID >=", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridLessThan(String value) {
			addCriterion("CREATORID <", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridLessThanOrEqualTo(String value) {
			addCriterion("CREATORID <=", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridLike(String value) {
			addCriterion("CREATORID like", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridNotLike(String value) {
			addCriterion("CREATORID not like", value, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridIn(List<String> values) {
			addCriterion("CREATORID in", values, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridNotIn(List<String> values) {
			addCriterion("CREATORID not in", values, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridBetween(String value1, String value2) {
			addCriterion("CREATORID between", value1, value2, "creatorid");
			return (Criteria) this;
		}

		public Criteria andCreatoridNotBetween(String value1, String value2) {
			addCriterion("CREATORID not between", value1, value2, "creatorid");
			return (Criteria) this;
		}

		public Criteria andIsvirtualIsNull() {
			addCriterion("ISVIRTUAL is null");
			return (Criteria) this;
		}

		public Criteria andIsvirtualIsNotNull() {
			addCriterion("ISVIRTUAL is not null");
			return (Criteria) this;
		}

		public Criteria andIsvirtualEqualTo(String value) {
			addCriterion("ISVIRTUAL =", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualNotEqualTo(String value) {
			addCriterion("ISVIRTUAL <>", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualGreaterThan(String value) {
			addCriterion("ISVIRTUAL >", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualGreaterThanOrEqualTo(String value) {
			addCriterion("ISVIRTUAL >=", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualLessThan(String value) {
			addCriterion("ISVIRTUAL <", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualLessThanOrEqualTo(String value) {
			addCriterion("ISVIRTUAL <=", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualLike(String value) {
			addCriterion("ISVIRTUAL like", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualNotLike(String value) {
			addCriterion("ISVIRTUAL not like", value, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualIn(List<String> values) {
			addCriterion("ISVIRTUAL in", values, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualNotIn(List<String> values) {
			addCriterion("ISVIRTUAL not in", values, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualBetween(String value1, String value2) {
			addCriterion("ISVIRTUAL between", value1, value2, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andIsvirtualNotBetween(String value1, String value2) {
			addCriterion("ISVIRTUAL not between", value1, value2, "isvirtual");
			return (Criteria) this;
		}

		public Criteria andUserrdnIsNull() {
			addCriterion("USERRDN is null");
			return (Criteria) this;
		}

		public Criteria andUserrdnIsNotNull() {
			addCriterion("USERRDN is not null");
			return (Criteria) this;
		}

		public Criteria andUserrdnEqualTo(String value) {
			addCriterion("USERRDN =", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnNotEqualTo(String value) {
			addCriterion("USERRDN <>", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnGreaterThan(String value) {
			addCriterion("USERRDN >", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnGreaterThanOrEqualTo(String value) {
			addCriterion("USERRDN >=", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnLessThan(String value) {
			addCriterion("USERRDN <", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnLessThanOrEqualTo(String value) {
			addCriterion("USERRDN <=", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnLike(String value) {
			addCriterion("USERRDN like", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnNotLike(String value) {
			addCriterion("USERRDN not like", value, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnIn(List<String> values) {
			addCriterion("USERRDN in", values, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnNotIn(List<String> values) {
			addCriterion("USERRDN not in", values, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnBetween(String value1, String value2) {
			addCriterion("USERRDN between", value1, value2, "userrdn");
			return (Criteria) this;
		}

		public Criteria andUserrdnNotBetween(String value1, String value2) {
			addCriterion("USERRDN not between", value1, value2, "userrdn");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdIsNull() {
			addCriterion("LASTCHANGEPWD is null");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdIsNotNull() {
			addCriterion("LASTCHANGEPWD is not null");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdEqualTo(Date value) {
			addCriterion("LASTCHANGEPWD =", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdNotEqualTo(Date value) {
			addCriterion("LASTCHANGEPWD <>", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdGreaterThan(Date value) {
			addCriterion("LASTCHANGEPWD >", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdGreaterThanOrEqualTo(Date value) {
			addCriterion("LASTCHANGEPWD >=", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdLessThan(Date value) {
			addCriterion("LASTCHANGEPWD <", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdLessThanOrEqualTo(Date value) {
			addCriterion("LASTCHANGEPWD <=", value, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdIn(List<Date> values) {
			addCriterion("LASTCHANGEPWD in", values, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdNotIn(List<Date> values) {
			addCriterion("LASTCHANGEPWD not in", values, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdBetween(Date value1, Date value2) {
			addCriterion("LASTCHANGEPWD between", value1, value2, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andLastchangepwdNotBetween(Date value1, Date value2) {
			addCriterion("LASTCHANGEPWD not between", value1, value2, "lastchangepwd");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginIsNull() {
			addCriterion("ISLIMITMULTILOGIN is null");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginIsNotNull() {
			addCriterion("ISLIMITMULTILOGIN is not null");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginEqualTo(String value) {
			addCriterion("ISLIMITMULTILOGIN =", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginNotEqualTo(String value) {
			addCriterion("ISLIMITMULTILOGIN <>", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginGreaterThan(String value) {
			addCriterion("ISLIMITMULTILOGIN >", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginGreaterThanOrEqualTo(String value) {
			addCriterion("ISLIMITMULTILOGIN >=", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginLessThan(String value) {
			addCriterion("ISLIMITMULTILOGIN <", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginLessThanOrEqualTo(String value) {
			addCriterion("ISLIMITMULTILOGIN <=", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginLike(String value) {
			addCriterion("ISLIMITMULTILOGIN like", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginNotLike(String value) {
			addCriterion("ISLIMITMULTILOGIN not like", value, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginIn(List<String> values) {
			addCriterion("ISLIMITMULTILOGIN in", values, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginNotIn(List<String> values) {
			addCriterion("ISLIMITMULTILOGIN not in", values, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginBetween(String value1, String value2) {
			addCriterion("ISLIMITMULTILOGIN between", value1, value2, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andIslimitmultiloginNotBetween(String value1, String value2) {
			addCriterion("ISLIMITMULTILOGIN not between", value1, value2, "islimitmultilogin");
			return (Criteria) this;
		}

		public Criteria andDutyIsNull() {
			addCriterion("DUTY is null");
			return (Criteria) this;
		}

		public Criteria andDutyIsNotNull() {
			addCriterion("DUTY is not null");
			return (Criteria) this;
		}

		public Criteria andDutyEqualTo(String value) {
			addCriterion("DUTY =", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotEqualTo(String value) {
			addCriterion("DUTY <>", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyGreaterThan(String value) {
			addCriterion("DUTY >", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyGreaterThanOrEqualTo(String value) {
			addCriterion("DUTY >=", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLessThan(String value) {
			addCriterion("DUTY <", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLessThanOrEqualTo(String value) {
			addCriterion("DUTY <=", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLike(String value) {
			addCriterion("DUTY like", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotLike(String value) {
			addCriterion("DUTY not like", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyIn(List<String> values) {
			addCriterion("DUTY in", values, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotIn(List<String> values) {
			addCriterion("DUTY not in", values, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyBetween(String value1, String value2) {
			addCriterion("DUTY between", value1, value2, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotBetween(String value1, String value2) {
			addCriterion("DUTY not between", value1, value2, "duty");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidIsNull() {
			addCriterion("OBJECTTYPEID is null");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidIsNotNull() {
			addCriterion("OBJECTTYPEID is not null");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidEqualTo(String value) {
			addCriterion("OBJECTTYPEID =", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidNotEqualTo(String value) {
			addCriterion("OBJECTTYPEID <>", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidGreaterThan(String value) {
			addCriterion("OBJECTTYPEID >", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidGreaterThanOrEqualTo(String value) {
			addCriterion("OBJECTTYPEID >=", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidLessThan(String value) {
			addCriterion("OBJECTTYPEID <", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidLessThanOrEqualTo(String value) {
			addCriterion("OBJECTTYPEID <=", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidLike(String value) {
			addCriterion("OBJECTTYPEID like", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidNotLike(String value) {
			addCriterion("OBJECTTYPEID not like", value, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidIn(List<String> values) {
			addCriterion("OBJECTTYPEID in", values, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidNotIn(List<String> values) {
			addCriterion("OBJECTTYPEID not in", values, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidBetween(String value1, String value2) {
			addCriterion("OBJECTTYPEID between", value1, value2, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjecttypeidNotBetween(String value1, String value2) {
			addCriterion("OBJECTTYPEID not between", value1, value2, "objecttypeid");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryIsNull() {
			addCriterion("OBJECTCATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryIsNotNull() {
			addCriterion("OBJECTCATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryEqualTo(String value) {
			addCriterion("OBJECTCATEGORY =", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryNotEqualTo(String value) {
			addCriterion("OBJECTCATEGORY <>", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryGreaterThan(String value) {
			addCriterion("OBJECTCATEGORY >", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryGreaterThanOrEqualTo(String value) {
			addCriterion("OBJECTCATEGORY >=", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryLessThan(String value) {
			addCriterion("OBJECTCATEGORY <", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryLessThanOrEqualTo(String value) {
			addCriterion("OBJECTCATEGORY <=", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryLike(String value) {
			addCriterion("OBJECTCATEGORY like", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryNotLike(String value) {
			addCriterion("OBJECTCATEGORY not like", value, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryIn(List<String> values) {
			addCriterion("OBJECTCATEGORY in", values, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryNotIn(List<String> values) {
			addCriterion("OBJECTCATEGORY not in", values, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryBetween(String value1, String value2) {
			addCriterion("OBJECTCATEGORY between", value1, value2, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andObjectcategoryNotBetween(String value1, String value2) {
			addCriterion("OBJECTCATEGORY not between", value1, value2, "objectcategory");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidIsNull() {
			addCriterion("USERTEMPLATEID is null");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidIsNotNull() {
			addCriterion("USERTEMPLATEID is not null");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidEqualTo(String value) {
			addCriterion("USERTEMPLATEID =", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidNotEqualTo(String value) {
			addCriterion("USERTEMPLATEID <>", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidGreaterThan(String value) {
			addCriterion("USERTEMPLATEID >", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidGreaterThanOrEqualTo(String value) {
			addCriterion("USERTEMPLATEID >=", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidLessThan(String value) {
			addCriterion("USERTEMPLATEID <", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidLessThanOrEqualTo(String value) {
			addCriterion("USERTEMPLATEID <=", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidLike(String value) {
			addCriterion("USERTEMPLATEID like", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidNotLike(String value) {
			addCriterion("USERTEMPLATEID not like", value, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidIn(List<String> values) {
			addCriterion("USERTEMPLATEID in", values, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidNotIn(List<String> values) {
			addCriterion("USERTEMPLATEID not in", values, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidBetween(String value1, String value2) {
			addCriterion("USERTEMPLATEID between", value1, value2, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andUsertemplateidNotBetween(String value1, String value2) {
			addCriterion("USERTEMPLATEID not between", value1, value2, "usertemplateid");
			return (Criteria) this;
		}

		public Criteria andIvruseridIsNull() {
			addCriterion("IVRUSERID is null");
			return (Criteria) this;
		}

		public Criteria andIvruseridIsNotNull() {
			addCriterion("IVRUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andIvruseridEqualTo(String value) {
			addCriterion("IVRUSERID =", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridNotEqualTo(String value) {
			addCriterion("IVRUSERID <>", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridGreaterThan(String value) {
			addCriterion("IVRUSERID >", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridGreaterThanOrEqualTo(String value) {
			addCriterion("IVRUSERID >=", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridLessThan(String value) {
			addCriterion("IVRUSERID <", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridLessThanOrEqualTo(String value) {
			addCriterion("IVRUSERID <=", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridLike(String value) {
			addCriterion("IVRUSERID like", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridNotLike(String value) {
			addCriterion("IVRUSERID not like", value, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridIn(List<String> values) {
			addCriterion("IVRUSERID in", values, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridNotIn(List<String> values) {
			addCriterion("IVRUSERID not in", values, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridBetween(String value1, String value2) {
			addCriterion("IVRUSERID between", value1, value2, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvruseridNotBetween(String value1, String value2) {
			addCriterion("IVRUSERID not between", value1, value2, "ivruserid");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordIsNull() {
			addCriterion("IVRPASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordIsNotNull() {
			addCriterion("IVRPASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordEqualTo(String value) {
			addCriterion("IVRPASSWORD =", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordNotEqualTo(String value) {
			addCriterion("IVRPASSWORD <>", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordGreaterThan(String value) {
			addCriterion("IVRPASSWORD >", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordGreaterThanOrEqualTo(String value) {
			addCriterion("IVRPASSWORD >=", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordLessThan(String value) {
			addCriterion("IVRPASSWORD <", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordLessThanOrEqualTo(String value) {
			addCriterion("IVRPASSWORD <=", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordLike(String value) {
			addCriterion("IVRPASSWORD like", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordNotLike(String value) {
			addCriterion("IVRPASSWORD not like", value, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordIn(List<String> values) {
			addCriterion("IVRPASSWORD in", values, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordNotIn(List<String> values) {
			addCriterion("IVRPASSWORD not in", values, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordBetween(String value1, String value2) {
			addCriterion("IVRPASSWORD between", value1, value2, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andIvrpasswordNotBetween(String value1, String value2) {
			addCriterion("IVRPASSWORD not between", value1, value2, "ivrpassword");
			return (Criteria) this;
		}

		public Criteria andFullcodeIsNull() {
			addCriterion("FULLCODE is null");
			return (Criteria) this;
		}

		public Criteria andFullcodeIsNotNull() {
			addCriterion("FULLCODE is not null");
			return (Criteria) this;
		}

		public Criteria andFullcodeEqualTo(String value) {
			addCriterion("FULLCODE =", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeNotEqualTo(String value) {
			addCriterion("FULLCODE <>", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeGreaterThan(String value) {
			addCriterion("FULLCODE >", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeGreaterThanOrEqualTo(String value) {
			addCriterion("FULLCODE >=", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeLessThan(String value) {
			addCriterion("FULLCODE <", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeLessThanOrEqualTo(String value) {
			addCriterion("FULLCODE <=", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeLike(String value) {
			addCriterion("FULLCODE like", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeNotLike(String value) {
			addCriterion("FULLCODE not like", value, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeIn(List<String> values) {
			addCriterion("FULLCODE in", values, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeNotIn(List<String> values) {
			addCriterion("FULLCODE not in", values, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeBetween(String value1, String value2) {
			addCriterion("FULLCODE between", value1, value2, "fullcode");
			return (Criteria) this;
		}

		public Criteria andFullcodeNotBetween(String value1, String value2) {
			addCriterion("FULLCODE not between", value1, value2, "fullcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeIsNull() {
			addCriterion("SHORTCODE is null");
			return (Criteria) this;
		}

		public Criteria andShortcodeIsNotNull() {
			addCriterion("SHORTCODE is not null");
			return (Criteria) this;
		}

		public Criteria andShortcodeEqualTo(String value) {
			addCriterion("SHORTCODE =", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeNotEqualTo(String value) {
			addCriterion("SHORTCODE <>", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeGreaterThan(String value) {
			addCriterion("SHORTCODE >", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeGreaterThanOrEqualTo(String value) {
			addCriterion("SHORTCODE >=", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeLessThan(String value) {
			addCriterion("SHORTCODE <", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeLessThanOrEqualTo(String value) {
			addCriterion("SHORTCODE <=", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeLike(String value) {
			addCriterion("SHORTCODE like", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeNotLike(String value) {
			addCriterion("SHORTCODE not like", value, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeIn(List<String> values) {
			addCriterion("SHORTCODE in", values, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeNotIn(List<String> values) {
			addCriterion("SHORTCODE not in", values, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeBetween(String value1, String value2) {
			addCriterion("SHORTCODE between", value1, value2, "shortcode");
			return (Criteria) this;
		}

		public Criteria andShortcodeNotBetween(String value1, String value2) {
			addCriterion("SHORTCODE not between", value1, value2, "shortcode");
			return (Criteria) this;
		}

		public Criteria andIsoaIsNull() {
			addCriterion("ISOA is null");
			return (Criteria) this;
		}

		public Criteria andIsoaIsNotNull() {
			addCriterion("ISOA is not null");
			return (Criteria) this;
		}

		public Criteria andIsoaEqualTo(String value) {
			addCriterion("ISOA =", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaNotEqualTo(String value) {
			addCriterion("ISOA <>", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaGreaterThan(String value) {
			addCriterion("ISOA >", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaGreaterThanOrEqualTo(String value) {
			addCriterion("ISOA >=", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaLessThan(String value) {
			addCriterion("ISOA <", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaLessThanOrEqualTo(String value) {
			addCriterion("ISOA <=", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaLike(String value) {
			addCriterion("ISOA like", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaNotLike(String value) {
			addCriterion("ISOA not like", value, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaIn(List<String> values) {
			addCriterion("ISOA in", values, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaNotIn(List<String> values) {
			addCriterion("ISOA not in", values, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaBetween(String value1, String value2) {
			addCriterion("ISOA between", value1, value2, "isoa");
			return (Criteria) this;
		}

		public Criteria andIsoaNotBetween(String value1, String value2) {
			addCriterion("ISOA not between", value1, value2, "isoa");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNull() {
			addCriterion("MODIFYTIME is null");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNotNull() {
			addCriterion("MODIFYTIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifytimeEqualTo(Date value) {
			addCriterion("MODIFYTIME =", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotEqualTo(Date value) {
			addCriterion("MODIFYTIME <>", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThan(Date value) {
			addCriterion("MODIFYTIME >", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFYTIME >=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThan(Date value) {
			addCriterion("MODIFYTIME <", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFYTIME <=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeIn(List<Date> values) {
			addCriterion("MODIFYTIME in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotIn(List<Date> values) {
			addCriterion("MODIFYTIME not in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeBetween(Date value1, Date value2) {
			addCriterion("MODIFYTIME between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFYTIME not between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andOutcompanyIsNull() {
			addCriterion("OUTCOMPANY is null");
			return (Criteria) this;
		}

		public Criteria andOutcompanyIsNotNull() {
			addCriterion("OUTCOMPANY is not null");
			return (Criteria) this;
		}

		public Criteria andOutcompanyEqualTo(String value) {
			addCriterion("OUTCOMPANY =", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyNotEqualTo(String value) {
			addCriterion("OUTCOMPANY <>", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyGreaterThan(String value) {
			addCriterion("OUTCOMPANY >", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyGreaterThanOrEqualTo(String value) {
			addCriterion("OUTCOMPANY >=", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyLessThan(String value) {
			addCriterion("OUTCOMPANY <", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyLessThanOrEqualTo(String value) {
			addCriterion("OUTCOMPANY <=", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyLike(String value) {
			addCriterion("OUTCOMPANY like", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyNotLike(String value) {
			addCriterion("OUTCOMPANY not like", value, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyIn(List<String> values) {
			addCriterion("OUTCOMPANY in", values, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyNotIn(List<String> values) {
			addCriterion("OUTCOMPANY not in", values, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyBetween(String value1, String value2) {
			addCriterion("OUTCOMPANY between", value1, value2, "outcompany");
			return (Criteria) this;
		}

		public Criteria andOutcompanyNotBetween(String value1, String value2) {
			addCriterion("OUTCOMPANY not between", value1, value2, "outcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyIsNull() {
			addCriterion("CONTRACTCOMPANY is null");
			return (Criteria) this;
		}

		public Criteria andContractcompanyIsNotNull() {
			addCriterion("CONTRACTCOMPANY is not null");
			return (Criteria) this;
		}

		public Criteria andContractcompanyEqualTo(String value) {
			addCriterion("CONTRACTCOMPANY =", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyNotEqualTo(String value) {
			addCriterion("CONTRACTCOMPANY <>", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyGreaterThan(String value) {
			addCriterion("CONTRACTCOMPANY >", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyGreaterThanOrEqualTo(String value) {
			addCriterion("CONTRACTCOMPANY >=", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyLessThan(String value) {
			addCriterion("CONTRACTCOMPANY <", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyLessThanOrEqualTo(String value) {
			addCriterion("CONTRACTCOMPANY <=", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyLike(String value) {
			addCriterion("CONTRACTCOMPANY like", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyNotLike(String value) {
			addCriterion("CONTRACTCOMPANY not like", value, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyIn(List<String> values) {
			addCriterion("CONTRACTCOMPANY in", values, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyNotIn(List<String> values) {
			addCriterion("CONTRACTCOMPANY not in", values, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyBetween(String value1, String value2) {
			addCriterion("CONTRACTCOMPANY between", value1, value2, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andContractcompanyNotBetween(String value1, String value2) {
			addCriterion("CONTRACTCOMPANY not between", value1, value2, "contractcompany");
			return (Criteria) this;
		}

		public Criteria andBaseIsNull() {
			addCriterion("BASE is null");
			return (Criteria) this;
		}

		public Criteria andBaseIsNotNull() {
			addCriterion("BASE is not null");
			return (Criteria) this;
		}

		public Criteria andBaseEqualTo(String value) {
			addCriterion("BASE =", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseNotEqualTo(String value) {
			addCriterion("BASE <>", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseGreaterThan(String value) {
			addCriterion("BASE >", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseGreaterThanOrEqualTo(String value) {
			addCriterion("BASE >=", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseLessThan(String value) {
			addCriterion("BASE <", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseLessThanOrEqualTo(String value) {
			addCriterion("BASE <=", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseLike(String value) {
			addCriterion("BASE like", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseNotLike(String value) {
			addCriterion("BASE not like", value, "base");
			return (Criteria) this;
		}

		public Criteria andBaseIn(List<String> values) {
			addCriterion("BASE in", values, "base");
			return (Criteria) this;
		}

		public Criteria andBaseNotIn(List<String> values) {
			addCriterion("BASE not in", values, "base");
			return (Criteria) this;
		}

		public Criteria andBaseBetween(String value1, String value2) {
			addCriterion("BASE between", value1, value2, "base");
			return (Criteria) this;
		}

		public Criteria andBaseNotBetween(String value1, String value2) {
			addCriterion("BASE not between", value1, value2, "base");
			return (Criteria) this;
		}

		public Criteria andBankaddrIsNull() {
			addCriterion("BANKADDR is null");
			return (Criteria) this;
		}

		public Criteria andBankaddrIsNotNull() {
			addCriterion("BANKADDR is not null");
			return (Criteria) this;
		}

		public Criteria andBankaddrEqualTo(String value) {
			addCriterion("BANKADDR =", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrNotEqualTo(String value) {
			addCriterion("BANKADDR <>", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrGreaterThan(String value) {
			addCriterion("BANKADDR >", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrGreaterThanOrEqualTo(String value) {
			addCriterion("BANKADDR >=", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrLessThan(String value) {
			addCriterion("BANKADDR <", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrLessThanOrEqualTo(String value) {
			addCriterion("BANKADDR <=", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrLike(String value) {
			addCriterion("BANKADDR like", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrNotLike(String value) {
			addCriterion("BANKADDR not like", value, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrIn(List<String> values) {
			addCriterion("BANKADDR in", values, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrNotIn(List<String> values) {
			addCriterion("BANKADDR not in", values, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrBetween(String value1, String value2) {
			addCriterion("BANKADDR between", value1, value2, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andBankaddrNotBetween(String value1, String value2) {
			addCriterion("BANKADDR not between", value1, value2, "bankaddr");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNull() {
			addCriterion("CARDNO is null");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNotNull() {
			addCriterion("CARDNO is not null");
			return (Criteria) this;
		}

		public Criteria andCardnoEqualTo(String value) {
			addCriterion("CARDNO =", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotEqualTo(String value) {
			addCriterion("CARDNO <>", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThan(String value) {
			addCriterion("CARDNO >", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThanOrEqualTo(String value) {
			addCriterion("CARDNO >=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThan(String value) {
			addCriterion("CARDNO <", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThanOrEqualTo(String value) {
			addCriterion("CARDNO <=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLike(String value) {
			addCriterion("CARDNO like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotLike(String value) {
			addCriterion("CARDNO not like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoIn(List<String> values) {
			addCriterion("CARDNO in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotIn(List<String> values) {
			addCriterion("CARDNO not in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoBetween(String value1, String value2) {
			addCriterion("CARDNO between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotBetween(String value1, String value2) {
			addCriterion("CARDNO not between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andTitlesIsNull() {
			addCriterion("TITLES is null");
			return (Criteria) this;
		}

		public Criteria andTitlesIsNotNull() {
			addCriterion("TITLES is not null");
			return (Criteria) this;
		}

		public Criteria andTitlesEqualTo(String value) {
			addCriterion("TITLES =", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesNotEqualTo(String value) {
			addCriterion("TITLES <>", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesGreaterThan(String value) {
			addCriterion("TITLES >", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesGreaterThanOrEqualTo(String value) {
			addCriterion("TITLES >=", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesLessThan(String value) {
			addCriterion("TITLES <", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesLessThanOrEqualTo(String value) {
			addCriterion("TITLES <=", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesLike(String value) {
			addCriterion("TITLES like", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesNotLike(String value) {
			addCriterion("TITLES not like", value, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesIn(List<String> values) {
			addCriterion("TITLES in", values, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesNotIn(List<String> values) {
			addCriterion("TITLES not in", values, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesBetween(String value1, String value2) {
			addCriterion("TITLES between", value1, value2, "titles");
			return (Criteria) this;
		}

		public Criteria andTitlesNotBetween(String value1, String value2) {
			addCriterion("TITLES not between", value1, value2, "titles");
			return (Criteria) this;
		}

		public Criteria andWorkdateIsNull() {
			addCriterion("WORKDATE is null");
			return (Criteria) this;
		}

		public Criteria andWorkdateIsNotNull() {
			addCriterion("WORKDATE is not null");
			return (Criteria) this;
		}

		public Criteria andWorkdateEqualTo(Date value) {
			addCriterion("WORKDATE =", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotEqualTo(Date value) {
			addCriterion("WORKDATE <>", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateGreaterThan(Date value) {
			addCriterion("WORKDATE >", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateGreaterThanOrEqualTo(Date value) {
			addCriterion("WORKDATE >=", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateLessThan(Date value) {
			addCriterion("WORKDATE <", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateLessThanOrEqualTo(Date value) {
			addCriterion("WORKDATE <=", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateIn(List<Date> values) {
			addCriterion("WORKDATE in", values, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotIn(List<Date> values) {
			addCriterion("WORKDATE not in", values, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateBetween(Date value1, Date value2) {
			addCriterion("WORKDATE between", value1, value2, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotBetween(Date value1, Date value2) {
			addCriterion("WORKDATE not between", value1, value2, "workdate");
			return (Criteria) this;
		}

		public Criteria andLeaderidIsNull() {
			addCriterion("LEADERID is null");
			return (Criteria) this;
		}

		public Criteria andLeaderidIsNotNull() {
			addCriterion("LEADERID is not null");
			return (Criteria) this;
		}

		public Criteria andLeaderidEqualTo(String value) {
			addCriterion("LEADERID =", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidNotEqualTo(String value) {
			addCriterion("LEADERID <>", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidGreaterThan(String value) {
			addCriterion("LEADERID >", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidGreaterThanOrEqualTo(String value) {
			addCriterion("LEADERID >=", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidLessThan(String value) {
			addCriterion("LEADERID <", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidLessThanOrEqualTo(String value) {
			addCriterion("LEADERID <=", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidLike(String value) {
			addCriterion("LEADERID like", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidNotLike(String value) {
			addCriterion("LEADERID not like", value, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidIn(List<String> values) {
			addCriterion("LEADERID in", values, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidNotIn(List<String> values) {
			addCriterion("LEADERID not in", values, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidBetween(String value1, String value2) {
			addCriterion("LEADERID between", value1, value2, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeaderidNotBetween(String value1, String value2) {
			addCriterion("LEADERID not between", value1, value2, "leaderid");
			return (Criteria) this;
		}

		public Criteria andLeadernameIsNull() {
			addCriterion("LEADERNAME is null");
			return (Criteria) this;
		}

		public Criteria andLeadernameIsNotNull() {
			addCriterion("LEADERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andLeadernameEqualTo(String value) {
			addCriterion("LEADERNAME =", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameNotEqualTo(String value) {
			addCriterion("LEADERNAME <>", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameGreaterThan(String value) {
			addCriterion("LEADERNAME >", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameGreaterThanOrEqualTo(String value) {
			addCriterion("LEADERNAME >=", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameLessThan(String value) {
			addCriterion("LEADERNAME <", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameLessThanOrEqualTo(String value) {
			addCriterion("LEADERNAME <=", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameLike(String value) {
			addCriterion("LEADERNAME like", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameNotLike(String value) {
			addCriterion("LEADERNAME not like", value, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameIn(List<String> values) {
			addCriterion("LEADERNAME in", values, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameNotIn(List<String> values) {
			addCriterion("LEADERNAME not in", values, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameBetween(String value1, String value2) {
			addCriterion("LEADERNAME between", value1, value2, "leadername");
			return (Criteria) this;
		}

		public Criteria andLeadernameNotBetween(String value1, String value2) {
			addCriterion("LEADERNAME not between", value1, value2, "leadername");
			return (Criteria) this;
		}

		public Criteria andIdcardnoIsNull() {
			addCriterion("IDCARDNO is null");
			return (Criteria) this;
		}

		public Criteria andIdcardnoIsNotNull() {
			addCriterion("IDCARDNO is not null");
			return (Criteria) this;
		}

		public Criteria andIdcardnoEqualTo(String value) {
			addCriterion("IDCARDNO =", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoNotEqualTo(String value) {
			addCriterion("IDCARDNO <>", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoGreaterThan(String value) {
			addCriterion("IDCARDNO >", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoGreaterThanOrEqualTo(String value) {
			addCriterion("IDCARDNO >=", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoLessThan(String value) {
			addCriterion("IDCARDNO <", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoLessThanOrEqualTo(String value) {
			addCriterion("IDCARDNO <=", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoLike(String value) {
			addCriterion("IDCARDNO like", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoNotLike(String value) {
			addCriterion("IDCARDNO not like", value, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoIn(List<String> values) {
			addCriterion("IDCARDNO in", values, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoNotIn(List<String> values) {
			addCriterion("IDCARDNO not in", values, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoBetween(String value1, String value2) {
			addCriterion("IDCARDNO between", value1, value2, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIdcardnoNotBetween(String value1, String value2) {
			addCriterion("IDCARDNO not between", value1, value2, "idcardno");
			return (Criteria) this;
		}

		public Criteria andIsloginIsNull() {
			addCriterion("ISLOGIN is null");
			return (Criteria) this;
		}

		public Criteria andIsloginIsNotNull() {
			addCriterion("ISLOGIN is not null");
			return (Criteria) this;
		}

		public Criteria andIsloginEqualTo(String value) {
			addCriterion("ISLOGIN =", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginNotEqualTo(String value) {
			addCriterion("ISLOGIN <>", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginGreaterThan(String value) {
			addCriterion("ISLOGIN >", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginGreaterThanOrEqualTo(String value) {
			addCriterion("ISLOGIN >=", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginLessThan(String value) {
			addCriterion("ISLOGIN <", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginLessThanOrEqualTo(String value) {
			addCriterion("ISLOGIN <=", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginLike(String value) {
			addCriterion("ISLOGIN like", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginNotLike(String value) {
			addCriterion("ISLOGIN not like", value, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginIn(List<String> values) {
			addCriterion("ISLOGIN in", values, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginNotIn(List<String> values) {
			addCriterion("ISLOGIN not in", values, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginBetween(String value1, String value2) {
			addCriterion("ISLOGIN between", value1, value2, "islogin");
			return (Criteria) this;
		}

		public Criteria andIsloginNotBetween(String value1, String value2) {
			addCriterion("ISLOGIN not between", value1, value2, "islogin");
			return (Criteria) this;
		}

		public Criteria andImeicodeIsNull() {
			addCriterion("IMEICODE is null");
			return (Criteria) this;
		}

		public Criteria andImeicodeIsNotNull() {
			addCriterion("IMEICODE is not null");
			return (Criteria) this;
		}

		public Criteria andImeicodeEqualTo(String value) {
			addCriterion("IMEICODE =", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeNotEqualTo(String value) {
			addCriterion("IMEICODE <>", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeGreaterThan(String value) {
			addCriterion("IMEICODE >", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeGreaterThanOrEqualTo(String value) {
			addCriterion("IMEICODE >=", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeLessThan(String value) {
			addCriterion("IMEICODE <", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeLessThanOrEqualTo(String value) {
			addCriterion("IMEICODE <=", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeLike(String value) {
			addCriterion("IMEICODE like", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeNotLike(String value) {
			addCriterion("IMEICODE not like", value, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeIn(List<String> values) {
			addCriterion("IMEICODE in", values, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeNotIn(List<String> values) {
			addCriterion("IMEICODE not in", values, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeBetween(String value1, String value2) {
			addCriterion("IMEICODE between", value1, value2, "imeicode");
			return (Criteria) this;
		}

		public Criteria andImeicodeNotBetween(String value1, String value2) {
			addCriterion("IMEICODE not between", value1, value2, "imeicode");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripIsNull() {
			addCriterion("LIMITEDSERVERIP is null");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripIsNotNull() {
			addCriterion("LIMITEDSERVERIP is not null");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripEqualTo(String value) {
			addCriterion("LIMITEDSERVERIP =", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripNotEqualTo(String value) {
			addCriterion("LIMITEDSERVERIP <>", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripGreaterThan(String value) {
			addCriterion("LIMITEDSERVERIP >", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripGreaterThanOrEqualTo(String value) {
			addCriterion("LIMITEDSERVERIP >=", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripLessThan(String value) {
			addCriterion("LIMITEDSERVERIP <", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripLessThanOrEqualTo(String value) {
			addCriterion("LIMITEDSERVERIP <=", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripLike(String value) {
			addCriterion("LIMITEDSERVERIP like", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripNotLike(String value) {
			addCriterion("LIMITEDSERVERIP not like", value, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripIn(List<String> values) {
			addCriterion("LIMITEDSERVERIP in", values, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripNotIn(List<String> values) {
			addCriterion("LIMITEDSERVERIP not in", values, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripBetween(String value1, String value2) {
			addCriterion("LIMITEDSERVERIP between", value1, value2, "limitedserverip");
			return (Criteria) this;
		}

		public Criteria andLimitedserveripNotBetween(String value1, String value2) {
			addCriterion("LIMITEDSERVERIP not between", value1, value2, "limitedserverip");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table BAF_ORG_USER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BAF_ORG_USER
     *
     * @mbggenerated do_not_delete_during_merge Thu May 19 16:13:11 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}