package org.apache.jsp.business.resMge.pwMge.fsuMge.map;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.springframework.web.context.*;
import com.regaltec.baf.framework.common.IBusiness;
import com.regaltec.baf.org.user.common.valueobj.UserVO;
import com.regaltec.common.util.Constant;
import com.regaltec.baf.org.user.ui.control.UserLoginBean;
import com.regaltec.baf.module.common.valueobj.ElementVO;
import com.regaltec.baf.external.rig.right.bi.IOperateRightBI;

public final class monitorMap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	
	String orgId = "";
	String personCenterX =  "";
	String personCenterY =  "";
	String personOrgname =  "";
	String personObjecttypeid = "";
	String userType="";
	ServletContext sc = session.getServletContext();
	WebApplicationContext ctx = (WebApplicationContext) sc.getAttribute("org.springframework.web.context.WebApplicationContext.ROOT");
	IBusiness business = (IBusiness) ctx.getBean("baf_businessDelegate");
	Hashtable hashtable = new Hashtable();
	//获取当前登录用户对象
	UserLoginBean loginBean = (UserLoginBean)session.getAttribute("userLoginBean");
	UserVO userVO = null;
	if(loginBean!=null){
		userVO = loginBean.getCurrentUser();
		userType=userVO.getLeaderId();
	}
	String maxOR = "";
	hashtable.put("rightFactorCode", Constant.RIGHTFACTOR_CODE_ORG);
	hashtable.put("currentThread", Thread.currentThread().getName());
	hashtable.put("ServletContext",sc);
	hashtable.put("userId", userVO.getUserId());		
	List<HashMap<String, Object>> list = (List<HashMap<String, Object>>)  business.invoke("bus_alarmActiveBI", "findOrgXY", hashtable);
	if(list != null && !list.isEmpty()){
		HashMap<String, Object> map = list.get(0);
		personCenterX = (String)map.get("X");
		personCenterY = (String)map.get("Y");
		personOrgname = (String)map.get("ORGNAME");
		personObjecttypeid =(String)map.get("OBJECTTYPEID");
	}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\" />\r\n");
      out.write("  <meta http-equiv=\"Cache-Control\" content=\"no-store\" />\r\n");
      out.write("  <meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("  <meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("  <title>地图</title>\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("\t\tbody, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:\"微软雅黑\";}\r\n");
      out.write("\t\t.anchorBL{display:none}\r\n");
      out.write("\t\t.BMap_scaleCtrl{display:block}\r\n");
      out.write("\t\t #maptools div{float: left;}\r\n");
      out.write("         #maptools{\r\n");
      out.write("           width:350px;\r\n");
      out.write("           height:30px;\r\n");
      out.write("       \t   position:absolute;\r\n");
      out.write("       \t   right:100px;\r\n");
      out.write("       \t   top: 0px;\r\n");
      out.write("       \t   z-index: 1001;\r\n");
      out.write("       \t   dispaly:none;\r\n");
      out.write("          }\r\n");
      out.write("          .tool{width:50px; height:50px;display:block;border-radius:25px;cursor:pointer;background-repeat:no-repeat;} \r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?v=2.0&ak=GVjmmVYGXD46FX56mYwzjdlF\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://api.map.baidu.com/library/AreaRestriction/1.2/src/AreaRestriction_min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/ida40/lib/jquery/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"> \r\n");
      out.write("\t// 这段JS 解决 bind 在IE下不兼容\r\n");
      out.write("\tif (!Function.prototype.bind) { \r\n");
      out.write("\t\tFunction.prototype.bind = function (oThis) { \r\n");
      out.write("\t\t\tif (typeof this !== \"function\") { \r\n");
      out.write("\t\t\t\tthrow new TypeError(\"Function.prototype.bind - what is trying to be bound is not callable\"); \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\tvar aArgs = Array.prototype.slice.call(arguments, 1), \r\n");
      out.write("\t\tfToBind = this, \r\n");
      out.write("\t\tfNOP = function () {}, \r\n");
      out.write("\t\tfBound = function () { \r\n");
      out.write("\t\t\treturn fToBind.apply(this instanceof fNOP && oThis ? this : oThis, aArgs.concat(Array.prototype.slice.call(arguments))); \r\n");
      out.write("\t\t}; \r\n");
      out.write("\t\tfNOP.prototype = this.prototype; \r\n");
      out.write("\t\tfBound.prototype = new fNOP(); \r\n");
      out.write("\t\treturn fBound; \r\n");
      out.write("\t}; \r\n");
      out.write("} \r\n");
      out.write("</script> \r\n");
      out.write("  </head>\r\n");
      out.write("<body >\r\n");
      out.write("<div id=\"allmap\"></div>\r\n");
      out.write("<div>\r\n");
      out.write("<select id=\"prv\" onchange=\"setcity()\" style=\"position:absolute;left:60px;top:2px;z-index:2001;\">\r\n");
      out.write("    <OPTION value=\"\">中国铁塔</OPTION>\r\n");
      out.write("    <OPTION value=安徽>安徽</OPTION>\r\n");
      out.write("    <OPTION value=北京>北京</OPTION>\r\n");
      out.write("    <OPTION value=重庆>重庆</OPTION>\r\n");
      out.write("    <OPTION value=福建>福建</OPTION>\r\n");
      out.write("    <OPTION value=甘肃>甘肃</OPTION>\r\n");
      out.write("    <OPTION value=广东>广东</OPTION>\r\n");
      out.write("    <OPTION value=广西>广西</OPTION>\r\n");
      out.write("    <OPTION value=贵州>贵州</OPTION>\r\n");
      out.write("    <OPTION value=海南>海南</OPTION>\r\n");
      out.write("    <OPTION value=河北>河北</OPTION>\r\n");
      out.write("    <OPTION value=黑龙江>黑龙江</OPTION>\r\n");
      out.write("    <OPTION value=河南>河南</OPTION>\r\n");
      out.write("    <OPTION value=湖北>湖北</OPTION>\r\n");
      out.write("    <OPTION value=湖南>湖南</OPTION>\r\n");
      out.write("    <OPTION value=江苏>江苏</OPTION>\r\n");
      out.write("    <OPTION value=江西>江西</OPTION>\r\n");
      out.write("    <OPTION value=吉林省>吉林</OPTION>\r\n");
      out.write("    <OPTION value=辽宁>辽宁</OPTION>\r\n");
      out.write("    <OPTION value=内蒙古>内蒙古</OPTION>\r\n");
      out.write("    <OPTION value=宁夏>宁夏</OPTION>\r\n");
      out.write("    <OPTION value=青海>青海</OPTION>\r\n");
      out.write("    <OPTION value=山东>山东</OPTION>\r\n");
      out.write("    <OPTION value=上海>上海</OPTION>\r\n");
      out.write("    <OPTION value=山西>山西</OPTION>\r\n");
      out.write("    <OPTION value=陕西>陕西</OPTION>\r\n");
      out.write("    <OPTION value=四川>四川</OPTION>\r\n");
      out.write("    <OPTION value=天津>天津</OPTION>\r\n");
      out.write("    <OPTION value=新疆>新疆</OPTION>\r\n");
      out.write("    <OPTION value=西藏>西藏</OPTION>\r\n");
      out.write("    <OPTION value=云南>云南</OPTION>\r\n");
      out.write("    <OPTION value=浙江>浙江</OPTION>\r\n");
      out.write("  </select>\r\n");
      out.write("</div>\r\n");
      out.write("<!--<div id=\"maptools\">       \r\n");
      out.write("          <div><span id =\"m\" class=\"tool\" style=\"background:url(./image/3yys1.png) -0px -42px no-repeat;repeat:\" onclick=\"javascript:show('m')\"/></div> \r\n");
      out.write("          <div><span id=\"u\" class=\"tool\" style=\"background:url(./image/3yys1.png)  -50px -42px no-repeat;\" onclick=\"javascript:show('u')\"/></div>    \r\n");
      out.write("          <div><span id=\"t\" class=\"tool\" style=\"background:url(./image/3yys1.png)  -95px -42px no-repeat;\" onclick=\"javascript:show('t')\"/></div>     \r\n");
      out.write("          <div><span id=\"mu\" class=\"tool\" style=\"background:url(./image/3yys1.png) -140px -42px no-repeat;\" onclick=\"javascript:show('mu')\"/></div>   \r\n");
      out.write("          <div><span id=\"mt\" class=\"tool\" style=\"background:url(./image/3yys1.png)  -185px -42px no-repeat;\" onclick=\"javascript:show('mt')\"/></div> \r\n");
      out.write("          <div><span id=\"ut\" class=\"tool\" style=\"background:url(./image/3yys1.png)  -230px -42px no-repeat;\" onclick=\"javascript:show('ut')\"/></div>   \r\n");
      out.write("          <div><span id=\"mut\" class=\"tool\" style=\"background:url(./image/3yys1.png)  -280px -42px no-repeat;\" onclick=\"javascript:show('mut')\"/></div>\r\n");
      out.write(" </div>--> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   // var m=1,u=1,t=1,mu=1,mt=1,ut=1,mut=1;\r\n");
      out.write("   // var s1,s2,s3,s4,s5,s6,s7;\r\n");
      out.write("\tvar personCenterX = \"");
      out.print(personCenterX);
      out.write("\";\r\n");
      out.write("\tvar personCenterY = \"");
      out.print(personCenterY);
      out.write("\";\r\n");
      out.write("\tvar personOrgname = \"");
      out.print(personOrgname);
      out.write("\";\r\n");
      out.write("\tvar personObjecttypeid= \"");
      out.print(personObjecttypeid);
      out.write("\";\r\n");
      out.write("\tvar userType= \"");
      out.print(userType);
      out.write("\";\r\n");
      out.write("\tvar map = new BMap.Map(\"allmap\",{minZoom:5});\r\n");
      out.write("\tvar cityAlarmMarkers=[];\r\n");
      out.write("\tvar pAlarmMarkers=[];\r\n");
      out.write("\tvar countyAlarmMarkers=[];\r\n");
      out.write("\tvar othersAlarmMarkers=[];\r\n");
      out.write("\tvar plys=[];\r\n");
      out.write("\tvar proplys=[];\r\n");
      out.write("\tvar cityplys=[];\r\n");
      out.write("\tvar markers = [];\r\n");
      out.write("\tvar momarkers=[];\r\n");
      out.write("\tvar unmarkers=[];\r\n");
      out.write("\tvar temarkers=[];\r\n");
      out.write("\tvar mumarkers=[];\r\n");
      out.write("\tvar mtmarkers=[];\r\n");
      out.write("\tvar utmarkers=[];\r\n");
      out.write("\tvar mutmarkers=[];\r\n");
      out.write("\tvar stationmarkers=[];\r\n");
      out.write("\tvar queryFlag = true;\r\n");
      out.write("\tif(personCenterX != \"\" && personCenterY != \"\"&& personOrgname !=\"\"){\r\n");
      out.write("\t\tmap.centerAndZoom(new BMap.Point(personCenterX,personCenterY),10);\r\n");
      out.write("\t\tgetProvinceBoundary(personOrgname.replace(\"分公司\",\"\"));\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tmap.centerAndZoom(new BMap.Point(107.30968,35.572893),5);\r\n");
      out.write("\t}\r\n");
      out.write("\tmap.enableScrollWheelZoom();  // 开启鼠标滚轮缩放 \r\n");
      out.write("\tmap.enableKeyboard();         // 开启键盘控制 \r\n");
      out.write("\tmap.enableContinuousZoom();   // 开启连续缩放效果 \r\n");
      out.write("\tmap.enableInertialDragging(); // 开启惯性拖拽效果\r\n");
      out.write("\t\r\n");
      out.write("\tvar stCtrl = new BMap.PanoramaControl(); //构造全景控件\r\n");
      out.write("\tstCtrl.setOffset(new BMap.Size(40, 60));\r\n");
      out.write("\tmap.addControl(stCtrl);//添加全景控件\r\n");
      out.write("\t\r\n");
      out.write("\t//\r\n");
      out.write("\tvar mapType = new BMap.MapTypeControl({mapTypes: [BMAP_NORMAL_MAP,BMAP_HYBRID_MAP]});\r\n");
      out.write("\tmap.addControl(mapType); \r\n");
      out.write("\r\n");
      out.write("\tmap.addControl(new BMap.NavigationControl()); //添加标准地图控件(左上角的放大缩小左右拖拽控件)\r\n");
      out.write("\tmap.addControl(new BMap.ScaleControl());      //添加比例尺控件(左下角显示的比例尺控件)\r\n");
      out.write("\tmap.addControl(new BMap.OverviewMapControl()); \r\n");
      out.write("\t\r\n");
      out.write("\t//给地图添加右键菜单\r\n");
      out.write("\tvar menuMap = new BMap.ContextMenu();\r\n");
      out.write("\tvar txtMenuItem = [\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttext:'显示站址',\r\n");
      out.write("\t\t\tcallback:function(){\r\n");
      out.write("\t\t\t\tqueryFlag = true;\r\n");
      out.write("\t\t\t\tif(markers != null){\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<markers.length;i++){\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttext:'隐藏站址',\r\n");
      out.write("\t\t\tcallback:function(){\r\n");
      out.write("\t\t\t\tqueryFlag = false;\r\n");
      out.write("\t\t\t\tif(markers != null){\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<markers.length;i++){\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t];\r\n");
      out.write("\tfor(var i=0; i < txtMenuItem.length; i++){\r\n");
      out.write("\t\tmenuMap.addItem(new BMap.MenuItem(txtMenuItem[i].text,txtMenuItem[i].callback,100));\r\n");
      out.write("\t}\r\n");
      out.write("\tmap.addContextMenu(menuMap);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addMouseOverHandler(label,marker){\r\n");
      out.write("\t\tmarker.addEventListener(\"mouseover\",function(e){\r\n");
      out.write("\t\t\tlabel.setStyle({\"display\":\"\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addMouseOutHandler(label,marker){\r\n");
      out.write("\t\tmarker.addEventListener(\"mouseout\",function(e){\r\n");
      out.write("\t\t\tlabel.setStyle({\"display\":\"none\"});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar markerClusterer = null;\r\n");
      out.write("\tvar showTVFunc = function(e,ee,marker){\r\n");
      out.write("\t\tif(marker.fsuIp != null && marker.fsuIp != \"\"){\r\n");
      out.write("\t\t\tparent.showTVFunc(marker.fsuIp);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"该FSU：\"+marker.fsuName+\"的FSUIP为空，无法看视频！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tvar selTopoTabFunc = function(e,ee,marker){\r\n");
      out.write("\t\tparent.selTopoTabFunc(marker.fsuId);\r\n");
      out.write("\t};\r\n");
      out.write("\tvar showStaBillList = function(e,ee,marker){\r\n");
      out.write("\t\tparent.showStaBillList(marker.staId,marker.staName);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction fixFsuMap(fsuJson){\r\n");
      out.write("\t\tfor(var i=0;i<fsuJson.length;i++){\r\n");
      out.write("\t\t\tvar myIcon = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(fsuJson[i].FSUID != null && fsuJson[i].FSUID != \"\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/newtower.png\", new BMap.Size(24,24)); //生成图标和大小\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/newnofsu.png\", new BMap.Size(24,24)); //生成图标和大小\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar point = new BMap.Point(fsuJson[i].LON, fsuJson[i].LAT);\r\n");
      out.write("\t\t\tvar marker = new BMap.Marker(point,{icon:myIcon});  // 创建标注\r\n");
      out.write("\t\t\t//创建右键菜单\r\n");
      out.write("\t\t\tvar markerMenu=new BMap.ContextMenu();\r\n");
      out.write("\t\t\tmarker.staId = fsuJson[i].ID;\r\n");
      out.write("\t\t\tmarker.staName = fsuJson[i].NAME;\r\n");
      out.write("\t\t\tmarkerMenu.addItem(new BMap.MenuItem(\"查看站址故障单\",showStaBillList.bind(marker)));\r\n");
      out.write("\t\t\tif(fsuJson[i].FSUID != null && fsuJson[i].FSUID != \"\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/newnofsu.png\", new BMap.Size(24,24)); //生成图标和大小\r\n");
      out.write("\t\t\t\tmarker.fsuId = fsuJson[i].FSUID;\r\n");
      out.write("\t\t\t\tmarker.fsuIp = fsuJson[i].INNERIP;\r\n");
      out.write("\t\t\t\tmarker.fsuName =fsuJson[i].FSUNAME;\r\n");
      out.write("\t\t\t\tif(userType!=null&&userType!=\"\"){\r\n");
      out.write("\t\t\t\t\tif(userType==\"1001\"||userType==\"1002\"||userType==\"1003\"){\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tmarkerMenu.addItem(new BMap.MenuItem(\"FSU监控视频\",showTVFunc.bind(marker)));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tmarkerMenu.addItem(new BMap.MenuItem(\"FSU拓扑图\",selTopoTabFunc.bind(marker)));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmarker.addContextMenu(markerMenu);\r\n");
      out.write("\t\t\t// 创建标注\r\n");
      out.write("\t\t \tvar label = new BMap.Label(fsuJson[i].NAME,{offset:new BMap.Size(20,-10)});\r\n");
      out.write("\t\t \tlabel.setStyle({\"display\":\"none\"});\r\n");
      out.write("\t\t \tmarker.setLabel(label);  // 将标注添加到地图中\r\n");
      out.write("\t\t\tmap.addOverlay(marker);   \r\n");
      out.write("\t\t\taddMouseOverHandler(label,marker);\r\n");
      out.write("\t\t\taddMouseOutHandler(label,marker);\r\n");
      out.write("\t\t\tmarkers.push(marker);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction fixYysMap(yysJson){\r\n");
      out.write("\t\tvar myIcon=null;\r\n");
      out.write("\t\tvar point=null;\r\n");
      out.write("\t\tvar marker=null;\r\n");
      out.write("\t\tfor(var i=0;i<yysJson.length;i++){\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1001'){\r\n");
      out.write("\t\t\t   myIcon = new BMap.Icon(\"image/YD.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t   point = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t   marker = new BMap.Marker(point,{icon:myIcon});\r\n");
      out.write("\t\t\t   momarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1002'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/LT.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon}); \r\n");
      out.write("\t\t\t\tunmarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1003'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/DX.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon}); \r\n");
      out.write("\t\t\t\ttemarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1001,1002'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/YDLT.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon});\r\n");
      out.write("\t\t\t\tmumarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1001,1003'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/YDDX.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon});\r\n");
      out.write("\t\t\t\tmtmarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1002,1003'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/DXLT.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon}); \r\n");
      out.write("\t\t\t\tutmarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(yysJson[i].OPERATORS=='1001,1002,1003'){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/YLD.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t\t\tpoint = new BMap.Point(yysJson[i].LON, yysJson[i].LAT);\r\n");
      out.write("\t\t\t\tmarker = new BMap.Marker(point,{icon:myIcon});\r\n");
      out.write("\t\t\t\tmutmarkers.push(marker);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fixAlarmMap(){\t\t\r\n");
      out.write("\t\tvar orgXObj = parent.document.getElementsByName(\"orgX\");\r\n");
      out.write("\t\tvar orgYObj = parent.document.getElementsByName(\"orgY\");\r\n");
      out.write("\t\tvar orgIdObj = parent.document.getElementsByName(\"orgId\");\r\n");
      out.write("\t\tvar levObj = parent.document.getElementsByName(\"alarmLevel\");\r\n");
      out.write("\t\tvar orgnameObj = parent.document.getElementsByName(\"orgname\");\r\n");
      out.write("\t\tvar parentorgid=parent.document.getElementsByName(\"parentorgid\");\r\n");
      out.write("\t\tif(orgXObj != null && orgYObj != null && orgIdObj != null && levObj != null){\r\n");
      out.write("\t\t\tfor(var i=0;i<orgXObj.length;i++){\r\n");
      out.write("\t\t\t\tvar point = new BMap.Point(orgXObj[i].value, orgYObj[i].value);\r\n");
      out.write("\t\t\t\tvar myIcon = null;\r\n");
      out.write("\t\t\t\tif(levObj[i].value==\"1\"){\r\n");
      out.write("\t\t\t\t\tmyIcon = new BMap.Icon(\"image/1-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t\t}else if(levObj[i].value==\"2\"){\r\n");
      out.write("\t\t\t\t\tmyIcon = new BMap.Icon(\"image/2-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t\t}else if(levObj[i].value==\"3\"){\r\n");
      out.write("\t\t\t\t\tmyIcon = new BMap.Icon(\"image/3-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t\t}else if(levObj[i].value==\"4\"){\r\n");
      out.write("\t\t\t\t\tmyIcon = new BMap.Icon(\"image/4-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpAlarmMarker = new BMap.Marker(point,{icon:myIcon});  // 创建标注\r\n");
      out.write("\t\t\t\tpAlarmMarker.orgId = orgIdObj[i].value;\r\n");
      out.write("\t\t\t\tpAlarmMarker.typeId=1;\r\n");
      out.write("\t\t\t\tpAlarmMarker.orgname= orgnameObj[i].value;\r\n");
      out.write("\t\t\t\tpAlarmMarker.disableMassClear();\r\n");
      out.write("\t\t\t\tmap.addOverlay(pAlarmMarker);\r\n");
      out.write("\t\t\t\tif(personObjecttypeid==3||parentorgid[i].value==0001935||parentorgid[i].value==0001936||parentorgid[i].value==0001937||parentorgid[i].value==0001938){\r\n");
      out.write("\t\t\t\t   pAlarmMarker.addEventListener(\"dblclick\",showMoreAlarm2);\r\n");
      out.write("\t\t\t\t}else if(personObjecttypeid==4){\r\n");
      out.write("\t\t\t\t   pAlarmMarker.addEventListener(\"dblclick\",showMoreAlarm3);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t   pAlarmMarker.addEventListener(\"dblclick\",showMoreAlarm);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpAlarmMarker.addEventListener(\"rightclick\",showAlarmDataModal);\r\n");
      out.write("\t\t\t\tpAlarmMarkers.push(pAlarmMarker);\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showMoreAlarm(e){\r\n");
      out.write("\t\tif(e.target.typeId==1&&(e.target.orgId==0001935||e.target.orgId==0001936||e.target.orgId==0001937||e.target.orgId==0001938)){\r\n");
      out.write("\t\t\tvar str=e.target.orgname.replace(\"分公司\",\"\");\r\n");
      out.write("\t\t\tfor(var i=0;i<pAlarmMarkers.length;i++){\r\n");
      out.write("\t\t\t\tpAlarmMarkers[i].hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tparent.getOthersAlarm(e.target.orgId);\r\n");
      out.write("\t\t\tgetProvinceBoundary(str);\r\n");
      out.write("\t\t}else if(e.target.typeId==1){\r\n");
      out.write("\t\t\tvar str=e.target.orgname.replace(\"分公司\",\"\");\r\n");
      out.write("\t\t\tfor(var i=0;i<pAlarmMarkers.length;i++){\r\n");
      out.write("\t\t\t\tpAlarmMarkers[i].hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tgetProvinceBoundary(str);\r\n");
      out.write("\t\t    parent.getCityAlarm(e.target.orgId);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar str=e.target.orgname.replace(\"分公司\",\"\");\r\n");
      out.write("\t\t\tfor(var j=0;j<cityAlarmMarkers.length;j++){\r\n");
      out.write("\t    \t\tcityAlarmMarkers[j].hide();\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t\tfor(var k=0;k<proplys.length;k++){\r\n");
      out.write("\t    \t\tproplys[k].hide();\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t\tgetCityBoundary(str);\r\n");
      out.write("\t\t    parent.getCountyAlarm(e.target.orgId);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showMoreAlarm2(e){\r\n");
      out.write("\t\tvar str=e.target.orgname.replace(\"分公司\",\"\");\r\n");
      out.write("\t\tfor(var i=0;i<pAlarmMarkers.length;i++){\r\n");
      out.write("\t\t\tpAlarmMarkers[i].hide();\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor(var l=0;l<proplys.length;l++){\r\n");
      out.write("    \t\tproplys[l].hide();\r\n");
      out.write("    \t}\r\n");
      out.write("\t\tparent.getCountyAlarm(e.target.orgId);\r\n");
      out.write("\t\tgetCityBoundary(str);\r\n");
      out.write("\t}\r\n");
      out.write("    function showMoreAlarm3(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showCityAlarms(alarmsJson){\r\n");
      out.write("\t\tfor(var i=0;i<alarmsJson.length;i++){\r\n");
      out.write("\t\t\tvar point = new BMap.Point(alarmsJson[i].X, alarmsJson[i].Y);\r\n");
      out.write("\t\t\tvar myIcon = null;\r\n");
      out.write("\t\t\tif(alarmsJson[i].ALARMLEVEL==\"1\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/1-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"2\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/2-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"3\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/3-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"4\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/4-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcityAlarmMarker = new BMap.Marker(point,{icon:myIcon});  // 创建标注\r\n");
      out.write("\t\t\tcityAlarmMarker.orgId = alarmsJson[i].ORGID;\r\n");
      out.write("\t\t\tcityAlarmMarker.orgname = alarmsJson[i].ORGNAME;\r\n");
      out.write("\t\t\tcityAlarmMarker.disableMassClear();\r\n");
      out.write("\t\t\tmap.addOverlay(cityAlarmMarker);\r\n");
      out.write("\t\t\tcityAlarmMarker.addEventListener(\"dblclick\",showMoreAlarm);\r\n");
      out.write("\t\t\tcityAlarmMarker.addEventListener(\"rightclick\",showAlarmDataModal);\r\n");
      out.write("\t\t\tcityAlarmMarkers.push(cityAlarmMarker);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showCountyAlarms(alarmsJson){\r\n");
      out.write("\t\tfor(var i=0;i<alarmsJson.length;i++){\r\n");
      out.write("\t\t\tvar point = new BMap.Point(alarmsJson[i].X, alarmsJson[i].Y);\r\n");
      out.write("\t\t\tvar myIcon = null;\r\n");
      out.write("\t\t\tif(alarmsJson[i].ALARMLEVEL==\"1\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/1-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"2\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/2-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"3\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/3-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"4\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/4-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar countyAlarmMarker = new BMap.Marker(point,{icon:myIcon});  // 创建标注\r\n");
      out.write("\t\t\tcountyAlarmMarker.orgId = alarmsJson[i].ORGID;\r\n");
      out.write("\t\t\tcountyAlarmMarker.addEventListener(\"rightclick\",showAlarmDataModal);\r\n");
      out.write("\t\t\tmap.addOverlay(countyAlarmMarker); \r\n");
      out.write("\t\t\tcountyAlarmMarkers.push(countyAlarmMarker);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showOthersAlarms(alarmsJson){\r\n");
      out.write("\t\tfor(var i=0;i<alarmsJson.length;i++){\r\n");
      out.write("\t\t\tvar point = new BMap.Point(alarmsJson[i].X, alarmsJson[i].Y);\r\n");
      out.write("\t\t\tvar myIcon = null;\r\n");
      out.write("\t\t\tif(alarmsJson[i].ALARMLEVEL==\"1\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/1-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"2\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/2-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"3\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/3-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}else if(alarmsJson[i].ALARMLEVEL==\"4\"){\r\n");
      out.write("\t\t\t\tmyIcon = new BMap.Icon(\"image/4-32.png\", new BMap.Size(32,32)); //生成图标和大小\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar othersAlarmMarker = new BMap.Marker(point,{icon:myIcon}); \r\n");
      out.write("\t\t\tothersAlarmMarker.orgId = alarmsJson[i].ORGID;\r\n");
      out.write("\t\t\t//countyAlarmMarker.disableMassClear();\r\n");
      out.write("\t\t\tmap.addOverlay(othersAlarmMarker);\r\n");
      out.write("\t\t\tothersAlarmMarker.addEventListener(\"rightclick\",showAlarmDataModal);\r\n");
      out.write("\t\t\tothersAlarmMarkers.push(othersAlarmMarker);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//获取覆盖物位置\r\n");
      out.write("\tfunction attribute(e){\r\n");
      out.write("\t\tvar p = e.target;\r\n");
      out.write("\t\talert(\"marker的位置是\" + p.getPosition().lng + \",\" + p.getPosition().lat);    \r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t//获取告警数据\r\n");
      out.write("\tfunction showAlarmDataModal(e){\r\n");
      out.write("\t\tvar p = e.target;\r\n");
      out.write("\t\tparent.showAlarmCount(p.orgId);\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getClass(tagName,className){\r\n");
      out.write("\t\r\n");
      out.write("\t    if(document.getElementsByClassName){        \r\n");
      out.write("\t    \treturn document.getElementsByClassName(className);\r\n");
      out.write("\t    }else{       \r\n");
      out.write("\t    \tvar tags=document.getElementsByTagName(tagName);\r\n");
      out.write("\t        var tagArr=[];\r\n");
      out.write("\t        for(var i=0;i < tags.length; i++)\r\n");
      out.write("\t        {\r\n");
      out.write("\t            if(tags[i].className == className)\r\n");
      out.write("\t            {\r\n");
      out.write("\t                tagArr[tagArr.length] = tags[i];\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t        return tagArr;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setImg(){\r\n");
      out.write("\t\tvar divArr = getClass(\"div\",\" anchorBL\");\r\n");
      out.write("\t\tif(divArr != null){\r\n");
      out.write("\t\t\tfor(var i=0;i<divArr.length;i++){\r\n");
      out.write("\t\t\t\t\tdivArr[i].innerHTML = \"<img style='border:none;width:77px;height:32px' src='/baf/images/mapLogo.png'>\";\r\n");
      out.write("\t\t\t\t\tdivArr[i].style.display=\"block\";\r\n");
      out.write("\t\t\t\t\t//map.removeEventListener(\"tilesloaded\", setImg);  \r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getProvinceBoundary(str){ \r\n");
      out.write("\t\tvar bdary = new BMap.Boundary();\r\n");
      out.write("\t\tbdary.get(str, function(rs){       //获取行政区域\r\n");
      out.write("\t\t\t        //清除地图覆盖物       \r\n");
      out.write("\t\t\tvar count = rs.boundaries.length; //行政区域的点有多少个\r\n");
      out.write("\t\t\tif (count === 0) {\r\n");
      out.write("\t\t\t\talert('未能获取当前输入行政区域');\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("          \tvar pointArray = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < count; i++) {\r\n");
      out.write("\t\t\t\tproply = new BMap.Polygon(rs.boundaries[i], {strokeWeight: 5, strokeColor: \"#ff0000\",fillColor:\"\"}); //建立多边形覆盖物\r\n");
      out.write("\t\t\t\tproply.disableMassClear();\r\n");
      out.write("\t\t\t\tmap.addOverlay(proply);  //添加覆盖物\r\n");
      out.write("\t\t\t\tpointArray = pointArray.concat(proply.getPath());\r\n");
      out.write("\t\t\t\tproplys.push(proply);\r\n");
      out.write("\t\t\t}    \r\n");
      out.write("\t\t\tmap.setViewport(pointArray);    //调整视野                 \r\n");
      out.write("\t\t});   \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getCityBoundary(str){ \r\n");
      out.write("\t\tvar bdary = new BMap.Boundary();\r\n");
      out.write("\t\tbdary.get(str, function(rs){       //获取行政区域\r\n");
      out.write("\t\t\t        //清除地图覆盖物       \r\n");
      out.write("\t\t\tvar count = rs.boundaries.length; //行政区域的点有多少个\r\n");
      out.write("\t\t\tif (count === 0) {\r\n");
      out.write("\t\t\t\talert('未能获取当前输入行政区域');\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("          \tvar pointArray = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < count; i++) {\r\n");
      out.write("\t\t\t\tcityply = new BMap.Polygon(rs.boundaries[i], {strokeWeight: 5, strokeColor: \"#ff0000\",fillColor:\"\"}); //建立多边形覆盖物\r\n");
      out.write("\t\t\t\tmap.addOverlay(cityply);  //添加覆盖物\r\n");
      out.write("\t\t\t\tpointArray = pointArray.concat(cityply.getPath());\r\n");
      out.write("\t\t\t\tcityplys.push(cityply);\r\n");
      out.write("\t\t\t}    \r\n");
      out.write("\t\t\tmap.setViewport(pointArray);    //调整视野                 \r\n");
      out.write("\t\t});   \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getBoundary(str){ \r\n");
      out.write("\t\tvar bdary = new BMap.Boundary();\r\n");
      out.write("\t\tbdary.get(str, function(rs){       //获取行政区域\r\n");
      out.write("\t\t\t  remove(plys);      //清除地图覆盖物       \r\n");
      out.write("\t\t\tvar count = rs.boundaries.length; //行政区域的点有多少个\r\n");
      out.write("\t\t\tif (count === 0) {\r\n");
      out.write("\t\t\t\talert('未能获取当前输入行政区域');\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("          \tvar pointArray = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < count; i++) {\r\n");
      out.write("\t\t\t\tvar ply = new BMap.Polygon(rs.boundaries[i], {strokeWeight: 5, strokeColor: \"#ff0000\",fillColor:\"\"}); //建立多边形覆盖物\r\n");
      out.write("\t\t\t\tmap.addOverlay(ply);  //添加覆盖物\r\n");
      out.write("\t\t\t\tpointArray = pointArray.concat(ply.getPath());\r\n");
      out.write("\t\t\t\tplys.push(ply);\r\n");
      out.write("\t\t\t}    \r\n");
      out.write("\t\t\tmap.setViewport(pointArray);    //调整视野                 \r\n");
      out.write("\t\t});   \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction loadedFsuOnMAP(){\r\n");
      out.write("\t\tsetImg();\r\n");
      out.write("\t\t//s1=0,s2=0,s3=0,s4=0,s5=0,s6=0,s7=0;\r\n");
      out.write("\t\tparent.setstatus();\r\n");
      out.write("\t\tvar lev = map.getZoom();\r\n");
      out.write("\t\tvar bounds = map.getBounds();\r\n");
      out.write("\t\tremove(markers);\r\n");
      out.write("\t\tparent.backtostart();\r\n");
      out.write("\t\tif(lev<10&&stationmarkers.length!=0)\r\n");
      out.write("          {\r\n");
      out.write("\t\t\tremove(stationmarkers);\r\n");
      out.write("\t\t\tparent.cleartext();\r\n");
      out.write("          }\t\t\t\r\n");
      out.write("\t\tremove(momarkers);\r\n");
      out.write("\t\tremove(unmarkers);\r\n");
      out.write("\t\tremove(temarkers);\r\n");
      out.write("\t\tremove(mumarkers);\r\n");
      out.write("\t\tremove(mtmarkers);\r\n");
      out.write("\t\tremove(utmarkers);\r\n");
      out.write("\t\tremove(mutmarkers);\r\n");
      out.write("\t\tif(lev >12 && queryFlag){\r\n");
      out.write("\t\t\t//var obj=document.getElementById(\"maptools\");\r\n");
      out.write("\t\t\t   // obj.style.display=\"block\";\r\n");
      out.write("\t\t\tparent.getFsuDataList(bounds.getNorthEast().lng,bounds.getSouthWest().lng,bounds.getNorthEast().lat,bounds.getSouthWest().lat);\r\n");
      out.write("\t\t\tparent.getYysDataList(bounds.getNorthEast().lng,bounds.getSouthWest().lng,bounds.getNorthEast().lat,bounds.getSouthWest().lat);\r\n");
      out.write("\t\t//}else{\r\n");
      out.write("\t\t\t   //var obj=document.getElementById(\"maptools\");\r\n");
      out.write("\t\t\t   // obj.style.display=\"none\";\r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\tmap.addEventListener(\"tilesloaded\",loadedFsuOnMAP);\r\n");
      out.write("\tvar scrollFunc=function(e){\r\n");
      out.write("\t    e=e || window.event;\r\n");
      out.write("\t    var leve=map.getZoom();\r\n");
      out.write("\t    \r\n");
      out.write("\t    if((personObjecttypeid ==\"\" || personObjecttypeid ==null)&&e.wheelDelta<0 && 5<leve<8){//IE/Opera/Chrome\r\n");
      out.write("\t    \t remove(countyAlarmMarkers);\r\n");
      out.write("\t    \t remove(cityplys);\r\n");
      out.write("          //map.clearOverlays();\r\n");
      out.write("\t    \tfor(var l=0;l<proplys.length;l++){\r\n");
      out.write("\t    \t\tproplys[l].show();\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \tfor(var p=0;p<cityAlarmMarkers.length;p++){\r\n");
      out.write("\t    \t\tcityAlarmMarkers[p].show();\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if((personObjecttypeid ==\"\"||personObjecttypeid ==null)&& e.wheelDelta<0 && leve==5){//IE/Opera/Chrome\t    \t\r\n");
      out.write("\t    \tremove(proplys);\r\n");
      out.write("    \t\tremove(cityAlarmMarkers);\r\n");
      out.write("    \t\tremove(othersAlarmMarkers);\r\n");
      out.write("    \t    for(var i=0;i<pAlarmMarkers.length;i++){\r\n");
      out.write("\t\t\tpAlarmMarkers[i].show();\r\n");
      out.write("\t\t\tremove(plys);\r\n");
      out.write("\t\t\tdocument.getElementById(\"prv\").selectedIndex=0;\r\n");
      out.write("\t\t    } \r\n");
      out.write("\t    }\r\n");
      out.write("\t    if((personObjecttypeid ==\"\" || personObjecttypeid ==null)&&e.wheelDelta>0 && leve>10){\r\n");
      out.write("\t      //remove(countyAlarmMarkers);\r\n");
      out.write("\t      //remove(cityplys);\r\n");
      out.write("\t      remove(proplys);\r\n");
      out.write("          remove(cityAlarmMarkers);\r\n");
      out.write("          remove(othersAlarmMarkers);\r\n");
      out.write("\t     }\r\n");
      out.write("\t    if(personObjecttypeid ==3 && e.wheelDelta<0 && leve<8){\r\n");
      out.write("\t    \tremove(countyAlarmMarkers);\r\n");
      out.write("\t    \tremove(cityplys);\r\n");
      out.write("\t    \tfor(var i=0;i<pAlarmMarkers.length;i++){\r\n");
      out.write("\t\t\t\tpAlarmMarkers[i].show();\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t    \tfor(var l=0;l<proplys.length;l++){\r\n");
      out.write("\t    \t\tproplys[l].show();\r\n");
      out.write("\t    \t}\t    \t\r\n");
      out.write("\t    }\r\n");
      out.write("  }\r\n");
      out.write("\twindow.onmousewheel=document.onmousewheel=scrollFunc;//IE/Opera/Chrome/Safari\r\n");
      out.write("\tfunction remove(arr){\r\n");
      out.write("\t\tfor(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\t\tmap.removeOverlay(arr[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tarr.length=0;\r\n");
      out.write("\t}\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t  function showmarkers(arr){\r\n");
      out.write("\t\t  for(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\t\t  map.addOverlay(arr[i]);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function dispaly(arr){\r\n");
      out.write("\t\t  for(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\t\t  arr[i].show();\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function hide(arr){\r\n");
      out.write("\t\t  for(var i=0;i<arr.length;i++){\r\n");
      out.write("\t\t\t  arr[i].hide();\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t  function setcity(){\r\n");
      out.write("\t\t    var obj=document.getElementById(\"prv\");\r\n");
      out.write("\t\t    var index = obj.selectedIndex;\r\n");
      out.write("\t\t    if(obj.options[index].value!=\"\"){\r\n");
      out.write("\t\t    \tgetBoundary(obj.options[index].value)\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function setStationMap(data){\r\n");
      out.write("\t\t  remove(stationmarkers);\r\n");
      out.write("\t\t  var point = new BMap.Point(data.lon, data.lat);\r\n");
      out.write("\t\t  myIcon = new BMap.Icon(\"image/tower.png\", new BMap.Size(32,32));\r\n");
      out.write("\t\t  var marker = new BMap.Marker(point,{icon:myIcon});  // 创建标注\r\n");
      out.write("\t\t  stationmarkers.push(marker);\r\n");
      out.write("\t\t  map.addOverlay(marker);\r\n");
      out.write("\t\t  map.centerAndZoom(new BMap.Point(data.lon, data.lat),15);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  function zoommap(){\r\n");
      out.write("\t\t  if(map.getZoom()<13){\r\n");
      out.write("\t\t  map.centerAndZoom(map.getCenter(),13);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function showeryysmarker(yystype){\r\n");
      out.write("\t\t  switch(yystype)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  case 1:\r\n");
      out.write("\t\t\t  showmarkers(momarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 2:\r\n");
      out.write("\t\t\t  showmarkers(unmarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 3:\r\n");
      out.write("\t\t\t  showmarkers(temarkers)\r\n");
      out.write("\t\t\t break; \r\n");
      out.write("\t\t  case 4:\r\n");
      out.write("\t\t\t  showmarkers(mumarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 5:\r\n");
      out.write("\t\t\t  showmarkers(mtmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 6:\r\n");
      out.write("\t\t\t  showmarkers(utmarkers)\r\n");
      out.write("\t\t\t\t break;\r\n");
      out.write("\t\t  case 7:\r\n");
      out.write("\t\t\t  showmarkers(mutmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function dispalyyysmarker(yystype){\r\n");
      out.write("\t\t  switch(yystype)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  case 1:\r\n");
      out.write("\t\t\t  dispaly(momarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 2:\r\n");
      out.write("\t\t\t  dispaly(unmarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 3:\r\n");
      out.write("\t\t\t  dispaly(temarkers)\r\n");
      out.write("\t\t\t break; \r\n");
      out.write("\t\t  case 4:\r\n");
      out.write("\t\t\t  dispaly(mumarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 5:\r\n");
      out.write("\t\t\t  dispaly(mtmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 6:\r\n");
      out.write("\t\t\t  dispaly(utmarkers)\r\n");
      out.write("\t\t\t\t break;\r\n");
      out.write("\t\t  case 7:\r\n");
      out.write("\t\t\t  dispaly(mutmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 8:\r\n");
      out.write("\t\t\t  dispaly(markers);\r\n");
      out.write("\t\t\t  break;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function hideyysmarker(yystype){\r\n");
      out.write("\t\t  switch(yystype)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  case 1:\r\n");
      out.write("\t\t\t  hide(momarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 2:\r\n");
      out.write("\t\t\t  hide(unmarkers);\r\n");
      out.write("\t\t    break;\r\n");
      out.write("\t\t  case 3:\r\n");
      out.write("\t\t\t  hide(temarkers)\r\n");
      out.write("\t\t\t break; \r\n");
      out.write("\t\t  case 4:\r\n");
      out.write("\t\t\t  hide(mumarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 5:\r\n");
      out.write("\t\t\t  hide(mtmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  case 6:\r\n");
      out.write("\t\t\t  hide(utmarkers)\r\n");
      out.write("\t\t\t\t break;\r\n");
      out.write("\t\t  case 7:\r\n");
      out.write("\t\t\t  hide(mutmarkers);\r\n");
      out.write("\t\t\t\t break; \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
