package com.ccssoft.rsas.pwb.user.model;

import java.util.Date;

public class BafOrgUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.USERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.USERTYPE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String usertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LOGINNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.USERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.PASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.GENDER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.EMPLOYDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date employdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.EMAIL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.OFFICEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String officephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.HOMEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String homephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.MOBILEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String mobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.PHS
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String phs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.PAGER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String pager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.FAX
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.ISVALID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String isvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.REMARK
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LIMITEDIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String limitedip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.CREATEDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.EXPIREDDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date expireddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.CREATORID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String creatorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.ISVIRTUAL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String isvirtual;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.USERRDN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String userrdn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LASTCHANGEPWD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date lastchangepwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.ISLIMITMULTILOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String islimitmultilogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.DUTY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String duty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.OBJECTTYPEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String objecttypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.OBJECTCATEGORY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String objectcategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.USERTEMPLATEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String usertemplateid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.IVRUSERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String ivruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.IVRPASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String ivrpassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.FULLCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String fullcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.SHORTCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String shortcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.ISOA
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String isoa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.MODIFYTIME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date modifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.OUTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String outcompany;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.CONTRACTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String contractcompany;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.BASE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String base;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.BANKADDR
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String bankaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.CARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String cardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.TITLES
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String titles;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.WORKDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private Date workdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LEADERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String leaderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LEADERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String leadername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.IDCARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String idcardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.ISLOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String islogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.IMEICODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String imeicode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.LIMITEDSERVERIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private String limitedserverip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BAF_ORG_USER.PHOTO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	private byte[] photo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.USERID
	 * @return  the value of BAF_ORG_USER.USERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.USERID
	 * @param userid  the value for BAF_ORG_USER.USERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.USERTYPE
	 * @return  the value of BAF_ORG_USER.USERTYPE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.USERTYPE
	 * @param usertype  the value for BAF_ORG_USER.USERTYPE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LOGINNAME
	 * @return  the value of BAF_ORG_USER.LOGINNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LOGINNAME
	 * @param loginname  the value for BAF_ORG_USER.LOGINNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.USERNAME
	 * @return  the value of BAF_ORG_USER.USERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.USERNAME
	 * @param username  the value for BAF_ORG_USER.USERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.PASSWORD
	 * @return  the value of BAF_ORG_USER.PASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.PASSWORD
	 * @param password  the value for BAF_ORG_USER.PASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.GENDER
	 * @return  the value of BAF_ORG_USER.GENDER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.GENDER
	 * @param gender  the value for BAF_ORG_USER.GENDER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.EMPLOYDATE
	 * @return  the value of BAF_ORG_USER.EMPLOYDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getEmploydate() {
		return employdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.EMPLOYDATE
	 * @param employdate  the value for BAF_ORG_USER.EMPLOYDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setEmploydate(Date employdate) {
		this.employdate = employdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.EMAIL
	 * @return  the value of BAF_ORG_USER.EMAIL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.EMAIL
	 * @param email  the value for BAF_ORG_USER.EMAIL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.OFFICEPHONE
	 * @return  the value of BAF_ORG_USER.OFFICEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getOfficephone() {
		return officephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.OFFICEPHONE
	 * @param officephone  the value for BAF_ORG_USER.OFFICEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.HOMEPHONE
	 * @return  the value of BAF_ORG_USER.HOMEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getHomephone() {
		return homephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.HOMEPHONE
	 * @param homephone  the value for BAF_ORG_USER.HOMEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.MOBILEPHONE
	 * @return  the value of BAF_ORG_USER.MOBILEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.MOBILEPHONE
	 * @param mobilephone  the value for BAF_ORG_USER.MOBILEPHONE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.PHS
	 * @return  the value of BAF_ORG_USER.PHS
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getPhs() {
		return phs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.PHS
	 * @param phs  the value for BAF_ORG_USER.PHS
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setPhs(String phs) {
		this.phs = phs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.PAGER
	 * @return  the value of BAF_ORG_USER.PAGER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getPager() {
		return pager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.PAGER
	 * @param pager  the value for BAF_ORG_USER.PAGER
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setPager(String pager) {
		this.pager = pager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.FAX
	 * @return  the value of BAF_ORG_USER.FAX
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.FAX
	 * @param fax  the value for BAF_ORG_USER.FAX
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.ISVALID
	 * @return  the value of BAF_ORG_USER.ISVALID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.ISVALID
	 * @param isvalid  the value for BAF_ORG_USER.ISVALID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIsvalid(String isvalid) {
		this.isvalid = isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.REMARK
	 * @return  the value of BAF_ORG_USER.REMARK
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.REMARK
	 * @param remark  the value for BAF_ORG_USER.REMARK
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LIMITEDIP
	 * @return  the value of BAF_ORG_USER.LIMITEDIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getLimitedip() {
		return limitedip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LIMITEDIP
	 * @param limitedip  the value for BAF_ORG_USER.LIMITEDIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLimitedip(String limitedip) {
		this.limitedip = limitedip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.CREATEDATE
	 * @return  the value of BAF_ORG_USER.CREATEDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.CREATEDATE
	 * @param createdate  the value for BAF_ORG_USER.CREATEDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.EXPIREDDATE
	 * @return  the value of BAF_ORG_USER.EXPIREDDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getExpireddate() {
		return expireddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.EXPIREDDATE
	 * @param expireddate  the value for BAF_ORG_USER.EXPIREDDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setExpireddate(Date expireddate) {
		this.expireddate = expireddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.CREATORID
	 * @return  the value of BAF_ORG_USER.CREATORID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getCreatorid() {
		return creatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.CREATORID
	 * @param creatorid  the value for BAF_ORG_USER.CREATORID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.ISVIRTUAL
	 * @return  the value of BAF_ORG_USER.ISVIRTUAL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIsvirtual() {
		return isvirtual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.ISVIRTUAL
	 * @param isvirtual  the value for BAF_ORG_USER.ISVIRTUAL
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIsvirtual(String isvirtual) {
		this.isvirtual = isvirtual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.USERRDN
	 * @return  the value of BAF_ORG_USER.USERRDN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getUserrdn() {
		return userrdn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.USERRDN
	 * @param userrdn  the value for BAF_ORG_USER.USERRDN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setUserrdn(String userrdn) {
		this.userrdn = userrdn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LASTCHANGEPWD
	 * @return  the value of BAF_ORG_USER.LASTCHANGEPWD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getLastchangepwd() {
		return lastchangepwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LASTCHANGEPWD
	 * @param lastchangepwd  the value for BAF_ORG_USER.LASTCHANGEPWD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLastchangepwd(Date lastchangepwd) {
		this.lastchangepwd = lastchangepwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.ISLIMITMULTILOGIN
	 * @return  the value of BAF_ORG_USER.ISLIMITMULTILOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIslimitmultilogin() {
		return islimitmultilogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.ISLIMITMULTILOGIN
	 * @param islimitmultilogin  the value for BAF_ORG_USER.ISLIMITMULTILOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIslimitmultilogin(String islimitmultilogin) {
		this.islimitmultilogin = islimitmultilogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.DUTY
	 * @return  the value of BAF_ORG_USER.DUTY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getDuty() {
		return duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.DUTY
	 * @param duty  the value for BAF_ORG_USER.DUTY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setDuty(String duty) {
		this.duty = duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.OBJECTTYPEID
	 * @return  the value of BAF_ORG_USER.OBJECTTYPEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getObjecttypeid() {
		return objecttypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.OBJECTTYPEID
	 * @param objecttypeid  the value for BAF_ORG_USER.OBJECTTYPEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setObjecttypeid(String objecttypeid) {
		this.objecttypeid = objecttypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.OBJECTCATEGORY
	 * @return  the value of BAF_ORG_USER.OBJECTCATEGORY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getObjectcategory() {
		return objectcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.OBJECTCATEGORY
	 * @param objectcategory  the value for BAF_ORG_USER.OBJECTCATEGORY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setObjectcategory(String objectcategory) {
		this.objectcategory = objectcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.USERTEMPLATEID
	 * @return  the value of BAF_ORG_USER.USERTEMPLATEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getUsertemplateid() {
		return usertemplateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.USERTEMPLATEID
	 * @param usertemplateid  the value for BAF_ORG_USER.USERTEMPLATEID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setUsertemplateid(String usertemplateid) {
		this.usertemplateid = usertemplateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.IVRUSERID
	 * @return  the value of BAF_ORG_USER.IVRUSERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIvruserid() {
		return ivruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.IVRUSERID
	 * @param ivruserid  the value for BAF_ORG_USER.IVRUSERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIvruserid(String ivruserid) {
		this.ivruserid = ivruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.IVRPASSWORD
	 * @return  the value of BAF_ORG_USER.IVRPASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIvrpassword() {
		return ivrpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.IVRPASSWORD
	 * @param ivrpassword  the value for BAF_ORG_USER.IVRPASSWORD
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIvrpassword(String ivrpassword) {
		this.ivrpassword = ivrpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.FULLCODE
	 * @return  the value of BAF_ORG_USER.FULLCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getFullcode() {
		return fullcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.FULLCODE
	 * @param fullcode  the value for BAF_ORG_USER.FULLCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setFullcode(String fullcode) {
		this.fullcode = fullcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.SHORTCODE
	 * @return  the value of BAF_ORG_USER.SHORTCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getShortcode() {
		return shortcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.SHORTCODE
	 * @param shortcode  the value for BAF_ORG_USER.SHORTCODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setShortcode(String shortcode) {
		this.shortcode = shortcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.ISOA
	 * @return  the value of BAF_ORG_USER.ISOA
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIsoa() {
		return isoa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.ISOA
	 * @param isoa  the value for BAF_ORG_USER.ISOA
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIsoa(String isoa) {
		this.isoa = isoa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.MODIFYTIME
	 * @return  the value of BAF_ORG_USER.MODIFYTIME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.MODIFYTIME
	 * @param modifytime  the value for BAF_ORG_USER.MODIFYTIME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.OUTCOMPANY
	 * @return  the value of BAF_ORG_USER.OUTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getOutcompany() {
		return outcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.OUTCOMPANY
	 * @param outcompany  the value for BAF_ORG_USER.OUTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setOutcompany(String outcompany) {
		this.outcompany = outcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.CONTRACTCOMPANY
	 * @return  the value of BAF_ORG_USER.CONTRACTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getContractcompany() {
		return contractcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.CONTRACTCOMPANY
	 * @param contractcompany  the value for BAF_ORG_USER.CONTRACTCOMPANY
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setContractcompany(String contractcompany) {
		this.contractcompany = contractcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.BASE
	 * @return  the value of BAF_ORG_USER.BASE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getBase() {
		return base;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.BASE
	 * @param base  the value for BAF_ORG_USER.BASE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setBase(String base) {
		this.base = base;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.BANKADDR
	 * @return  the value of BAF_ORG_USER.BANKADDR
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getBankaddr() {
		return bankaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.BANKADDR
	 * @param bankaddr  the value for BAF_ORG_USER.BANKADDR
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setBankaddr(String bankaddr) {
		this.bankaddr = bankaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.CARDNO
	 * @return  the value of BAF_ORG_USER.CARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getCardno() {
		return cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.CARDNO
	 * @param cardno  the value for BAF_ORG_USER.CARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.TITLES
	 * @return  the value of BAF_ORG_USER.TITLES
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getTitles() {
		return titles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.TITLES
	 * @param titles  the value for BAF_ORG_USER.TITLES
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setTitles(String titles) {
		this.titles = titles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.WORKDATE
	 * @return  the value of BAF_ORG_USER.WORKDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public Date getWorkdate() {
		return workdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.WORKDATE
	 * @param workdate  the value for BAF_ORG_USER.WORKDATE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setWorkdate(Date workdate) {
		this.workdate = workdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LEADERID
	 * @return  the value of BAF_ORG_USER.LEADERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getLeaderid() {
		return leaderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LEADERID
	 * @param leaderid  the value for BAF_ORG_USER.LEADERID
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLeaderid(String leaderid) {
		this.leaderid = leaderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LEADERNAME
	 * @return  the value of BAF_ORG_USER.LEADERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getLeadername() {
		return leadername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LEADERNAME
	 * @param leadername  the value for BAF_ORG_USER.LEADERNAME
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLeadername(String leadername) {
		this.leadername = leadername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.IDCARDNO
	 * @return  the value of BAF_ORG_USER.IDCARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIdcardno() {
		return idcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.IDCARDNO
	 * @param idcardno  the value for BAF_ORG_USER.IDCARDNO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIdcardno(String idcardno) {
		this.idcardno = idcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.ISLOGIN
	 * @return  the value of BAF_ORG_USER.ISLOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getIslogin() {
		return islogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.ISLOGIN
	 * @param islogin  the value for BAF_ORG_USER.ISLOGIN
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setIslogin(String islogin) {
		this.islogin = islogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.IMEICODE
	 * @return  the value of BAF_ORG_USER.IMEICODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getImeicode() {
		return imeicode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.IMEICODE
	 * @param imeicode  the value for BAF_ORG_USER.IMEICODE
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setImeicode(String imeicode) {
		this.imeicode = imeicode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.LIMITEDSERVERIP
	 * @return  the value of BAF_ORG_USER.LIMITEDSERVERIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public String getLimitedserverip() {
		return limitedserverip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.LIMITEDSERVERIP
	 * @param limitedserverip  the value for BAF_ORG_USER.LIMITEDSERVERIP
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setLimitedserverip(String limitedserverip) {
		this.limitedserverip = limitedserverip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BAF_ORG_USER.PHOTO
	 * @return  the value of BAF_ORG_USER.PHOTO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public byte[] getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BAF_ORG_USER.PHOTO
	 * @param photo  the value for BAF_ORG_USER.PHOTO
	 * @mbggenerated  Thu May 19 16:13:12 CST 2016
	 */
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}
}